{
  "swagger": "2.0",
  "info": {
    "description": "An Orchestration Layer that takes ISL services and packages them in a more targeted way for front-end applications.\nThis in turn makes client integration easier and reduces the complexity and size of front-end applications.\n\nRocket is also customisable - allowing UI engineers to ‘remix’ the existing back-end services into something that\nbest suits the application they are developing.\n",
    "title": "Rocket Services",
    "version": "3.730.205-ref-1-39-0",
    "x-apisguru-categories": [
      "entertainment"
    ],
    "x-origin": [
      {
        "format": "swagger",
        "url": "https://isl.britbox.co.uk/api/spec",
        "version": "2.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "britbox.co.uk",
    "x-datafire": {
      "name": "britbox",
      "type": "openapi"
    }
  },
  "host": "isl.britbox.co.uk",
  "basePath": "/api",
  "schemes": [
    "https"
  ],
  "paths": {
    "/account": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get the details of an account along with the profiles and entitlements under it.",
        "operationId": "getAccount"
      },
      "patch": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Update the details of an account.\n\nWith the exception of the address, this supports partial updates, so you can send just the\nproperties you wish to update.\n\nWhen the address is provided any properties which are omitted from the address will be cleared.\n",
        "operationId": "updateAccount"
      },
      "x-serviceId": "account"
    },
    "/account/billing/methods": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get the available payment methods under an account.",
        "operationId": "getPaymentMethods"
      },
      "post": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Add a new payment method to an account.",
        "operationId": "addPaymentMethod"
      },
      "x-serviceId": "billing"
    },
    "/account/billing/methods/{id}": {
      "delete": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Remove a payment method from an account.",
        "operationId": "removePaymentMethod"
      },
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get a payment method under an account.",
        "operationId": "getPaymentMethod"
      },
      "x-serviceId": "billing"
    },
    "/account/billing/purchases": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get a list of all purchases made under an account.",
        "operationId": "getPurchases"
      },
      "post": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Purchase a plan or item offer.\nThe result of a successful transaction is a new entitlement.\n",
        "operationId": "makePurchase"
      },
      "x-serviceId": "billing"
    },
    "/account/billing/subscriptions/{id}": {
      "delete": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Cancel a plan subscription.\n\nA cancelled subscription will continue to be valid until the subscription\nexpiry date or next renewal date.\n",
        "operationId": "cancelSubscription"
      },
      "put": {
        "security": [
          {
            "accountAuth": [
              "Commerce"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Renew a cancelled subscription or switch subscription to a different plan.\n\nWhen renewing a cancelled subscription membership, hit this endpoint with\nthe id of subscription to renew.\n\nTo switch plans provide the id of the current active subscription membership\nof the account, and in the query specify the id of the plan to switch to.\n",
        "operationId": "updateSubscription"
      },
      "x-serviceId": "billing"
    },
    "/account/devices": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get all devices registered under this account.\n\nAlso includes information around device registration and deregistration limits.\n",
        "operationId": "getDevices"
      },
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Register a playback device under an account.\n\nIf a device with the same id already exists a `409` conflict will be returned.\n",
        "operationId": "registerDevice"
      },
      "x-serviceId": "device"
    },
    "/account/devices/authorization": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Authorize a device from a generated device authorization code.\n\nThis is the second step in the process of authorizing a device by pin code.\n\nFirstly the device must request a generated authorization code via the\n`/authorization/device/code` endpoint.\n\nThis endpoint then authorizes the device associated with the code to sign in\nto a user account. Typically this endpoint will be called from a page\npresented in the web app under the account section.\n\nOnce authoriz[...]",
        "operationId": "authorizeDevice"
      },
      "x-serviceId": "itvAuth"
    },
    "/account/devices/{id}": {
      "delete": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Deregister a playback device from an account.",
        "operationId": "deregisterDevice"
      },
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get a registered device.",
        "operationId": "getDevice"
      },
      "x-serviceId": "device"
    },
    "/account/devices/{id}/name": {
      "put": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Rename a device",
        "operationId": "renameDevice"
      },
      "x-serviceId": "device"
    },
    "/account/entitlements": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get all entitlements under the account.\n\nThis list is returned under the call to get account information so a call here is\nonly required when wishing to refresh a local copy of entitlements.\n",
        "operationId": "getEntitlements"
      },
      "x-serviceId": "entitlement"
    },
    "/account/items/{id}/videos": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get the video files associated with an item given maximum resolution, device type\nand one or more delivery types.\n\nThis endpoint accepts an Account Catalog token, however if when requesting\nplayback files you receive an *403 status code with error code 1* then the file\nyou're requesting is classification restricted. This means you should switch\nto target the `/account/items/{id}/videos-guarded` endpoint, passing it an Account\nPlayback token. If not already obtained[...]",
        "operationId": "getItemMediaFiles"
      },
      "x-serviceId": "media"
    },
    "/account/items/{id}/videos-guarded": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Playback"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get the video files associated with an item given maximum resolution, device type\nand one or more delivery types.\n\nThis endpoint is identical to the `/account/items/{id}/videos` however it expects\nan Account Playback token. This token, and in association this endpoint, is specifically\nfor use when playback files are classification restricted and require an account\nlevel pin to access them.\n\nReturns an array of video file objects which each include a url to a video[...]",
        "operationId": "getItemMediaFilesGuarded"
      },
      "x-serviceId": "media"
    },
    "/account/nonce": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Generate a new account nonce.\n\nA nonce may be required to help sign a response from a third party\nservice which will be passed back to these services.\n\nFor example a Facebook single-sign-on request initiated by a client\napplication may first get a nonce from here to include in the request.\nFacebook will then include the nonce in the auth token it issues. This\ntoken can be passed back to our services and the nonce checked for validity.\n",
        "operationId": "generateNonce"
      },
      "x-serviceId": "account"
    },
    "/account/password": {
      "put": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Change the password of an account.\n\nThe expected token scope is Settings.\n",
        "operationId": "changePassword"
      },
      "x-serviceId": "itvPassword"
    },
    "/account/pin": {
      "put": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Change the pin of an account.",
        "operationId": "changePin"
      },
      "x-serviceId": "itvAccount"
    },
    "/account/profile": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the details of the active profile, including watched, bookmarked and rated items.",
        "operationId": "getProfile"
      },
      "x-serviceId": "profile"
    },
    "/account/profile/bookmarks": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the map of bookmarked item ids (itemId => creationDate) under the active profile.",
        "operationId": "getBookmarks"
      },
      "x-serviceId": "bookmark"
    },
    "/account/profile/bookmarks/list": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Returns the list of bookmarked items under the active profile.",
        "operationId": "getBookmarkList"
      },
      "x-serviceId": "bookmark"
    },
    "/account/profile/bookmarks/{itemId}": {
      "delete": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Unbookmark an item under the active profile.",
        "operationId": "deleteItemBookmark"
      },
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the bookmark for an item under the active profile.",
        "operationId": "getItemBookmark"
      },
      "put": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Bookmark an item under the active profile.\n\nCreates one if it doesn't exist, overwrites one if it does.\n",
        "operationId": "bookmarkItem"
      },
      "x-serviceId": "bookmark"
    },
    "/account/profile/continue-watching/list": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Returns a list of items which have been watched but not completed under the active\nprofile.\n\nMultiple episodes under the same show may be watched or in progress, however only a\nsingle item belonging to a particular show will be included in the returned list.\n\nThe next episode to continue watching for a particular show will be the most recent\nincompletely watched episode, or the next episode following the most recently\ncompletely watched episode. Based on the speci[...]",
        "operationId": "getContinueWatchingList"
      },
      "x-serviceId": "continueWatching"
    },
    "/account/profile/items/{itemId}/next": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Returns the next item to play given a source item id.\n\nFor an unwatched show it returns the first episode available to the account.\n\nFor a watched show it returns the last incompletely watched episode by the profile,\nor the episode that immediately follows the last completely watched episode\nor nothing.\n\nFor an episode it always returns the immediately following episode, if available to\nthe account, or nothing.\n\nIf the response does not contain a `next` propert[...]",
        "operationId": "getNextPlaybackItem"
      },
      "x-serviceId": "continueWatching"
    },
    "/account/profile/ratings": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the map of rated item ids (itemId => rating out of 10) under the active profile.",
        "operationId": "getRatings"
      },
      "x-serviceId": "userRating"
    },
    "/account/profile/ratings/list": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Returns the list of rated items under the active profile.",
        "operationId": "getRatingsList"
      },
      "x-serviceId": "userRating"
    },
    "/account/profile/ratings/{itemId}": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the rating info for an item under the active profile.",
        "operationId": "getItemRating"
      },
      "put": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Rate an item under the active profile.\n\nCreates one if it doesn't exist, overwrites one if it does.\n",
        "operationId": "rateItem"
      },
      "x-serviceId": "userRating"
    },
    "/account/profile/watched": {
      "delete": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Remove the watched status of items under the active profile. Passing in\nspecific `itemId`s to the `item_ids` query parameter will cause only these\nitems to be removed. **If this list is missing all watched items will be\nremoved**\n",
        "operationId": "deleteWatched"
      },
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the map of watched item ids (itemId => last playhead position) under the active profile.",
        "operationId": "getWatched"
      },
      "x-serviceId": "watched"
    },
    "/account/profile/watched/list": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Returns the list of watched items under the active profile.",
        "operationId": "getWatchedList"
      },
      "x-serviceId": "watched"
    },
    "/account/profile/watched/{itemId}": {
      "get": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Get the watched status info for an item under the active profile.",
        "operationId": "getItemWatchedStatus"
      },
      "put": {
        "security": [
          {
            "profileAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "profile"
        ],
        "description": "Record the watched playhead position of a video under the active profile.\n\nCan be used later to resume a video from where it was last watched.\n\nCreates one if it doesn't exist, overwrites one if it does.\n",
        "operationId": "setItemWatchedStatus"
      },
      "x-serviceId": "watched"
    },
    "/account/profiles": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Create a new profile under the active account.",
        "operationId": "createProfile"
      },
      "x-serviceId": "profile"
    },
    "/account/profiles/{id}": {
      "delete": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Delete a profile with a specific id under the active account.\n\nNote that you cannot delete the primary profile.\n",
        "operationId": "deleteProfileWithId"
      },
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Get the summary of a profile with a specific id under the active account.",
        "operationId": "getProfileWithId"
      },
      "patch": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Update the summary of a profile with a specific id under the active account.\n\nThis supports partial updates so you can send just the properties you wish to update.\n",
        "operationId": "updateProfileWithId"
      },
      "x-serviceId": "profile"
    },
    "/account/request-email-verification": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "account"
        ],
        "description": "Request that the email address tied to an account be verified.\n\nThis will send a verification email to the email address of the primary profile containing\na link which, once clicked, completes the verification process via the /verify-email endpoint.\n\nNote that when an account is created this email is sent automatically so there's no need\nto call this directly.\n\nIf the user doesn't click the link before it expires then this endpoint can be called\nto request a new [...]",
        "operationId": "requestEmailVerification"
      },
      "x-serviceId": "account"
    },
    "/authorization": {
      "delete": {
        "tags": [
          "authorization"
        ],
        "description": "When a user signs out of an application we need to clear some\nbasic cookies we assigned them during token authorization.\n",
        "operationId": "signOut"
      },
      "post": {
        "tags": [
          "authorization"
        ],
        "description": "Request one or more `Account` level authorization tokens each with a chosen scope.\n\nTokens are used to access restricted service endpoints. These restricted endpoints\nwill require a specific token type (e.g Account) with a specific scope (e.g. Catalog)\nbefore access is granted.\n\nFor convenience, where a Profile level token with the same scope exists it will also be returned.\n\nAuthorization with pin is not supported on this endpoint anymore. Use `/itv/pinauthorizat[...]",
        "operationId": "getAccountToken"
      },
      "x-serviceId": "itvAuth"
    },
    "/authorization/device": {
      "post": {
        "tags": [
          "authorization"
        ],
        "description": "Get Catalog tokens for an account using a device authorization code.\nWhere a Profile level token of Catalog scope exists it will also be returned.\n\nThis is the final step in the process of authorizing a device by pin code.\n\nFirstly the device must request a generated authorization code via the\n`/authorization/device/code` endpoint.\n\nThe code is subsequently used to authorize the device to sign in to a given\naccount via the `/account/devices/authorization` endpoin[...]",
        "operationId": "getAccountTokenByCode"
      },
      "x-serviceId": "itvAuth"
    },
    "/authorization/device/code": {
      "post": {
        "tags": [
          "authorization"
        ],
        "description": "Get a generated device authorization code.\n\nThis is the first step in the process of authorizing a device by pin code.\nThe device will make a request to this endpoint providing a unique identifier\nfor the device such as a serial number. This endpoint will then return a\ngenerated code which is tied to the given device.\n\nThe code may subsequently be used to authorize the device to sign in to an\naccount via the `/account/devices/authorization` endpoint. Typically thi[...]",
        "operationId": "generateDeviceAuthorizationCode"
      },
      "x-serviceId": "itvAuth"
    },
    "/authorization/profile": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "authorization"
        ],
        "description": "Request one or more `Profile` level authorization tokens each with a chosen scope.\n\nTokens are used to access restricted service endpoints. These restriced endpoints\nwill require a specific token type (e.g Profile) with a specific scope (e.g. Catalog)\nbefore access is granted.\n",
        "operationId": "getProfileToken"
      },
      "x-serviceId": "itvAuth"
    },
    "/authorization/refresh": {
      "post": {
        "tags": [
          "authorization"
        ],
        "description": "Refresh an account or profile level authorization token which is marked as refreshable.",
        "operationId": "refreshToken"
      },
      "x-serviceId": "itvAuth"
    },
    "/authorization/sso": {
      "post": {
        "tags": [
          "authorization"
        ],
        "description": "Exchange a third party single-sign-on token for our own authorization tokens.",
        "operationId": "singleSignOn"
      },
      "x-serviceId": "auth"
    },
    "/bt/plans": {
      "get": {
        "tags": [
          "bt"
        ],
        "description": "Returns all the plans available for BT flow including additional description data.",
        "operationId": "getPlansBT"
      },
      "x-serviceId": "itvBt"
    },
    "/bt/token/assign": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "bt"
        ],
        "description": "Assigns an UserToken to a profile on the ITV side. Currently throws an exception.",
        "operationId": "assignToken"
      },
      "x-serviceId": "itvBt"
    },
    "/bt/token/validate": {
      "get": {
        "tags": [
          "bt"
        ],
        "description": "Checks a provided token for BT eligible user.\n",
        "operationId": "checkUserToken"
      },
      "x-serviceId": "itvBt"
    },
    "/check-subscription/{id}": {
      "get": {
        "tags": [
          "support"
        ],
        "description": "Returns the details of subscription data for a user with specified id.",
        "operationId": "getSubscriptionData"
      },
      "x-serviceId": "itvSubscription"
    },
    "/config": {
      "get": {
        "tags": [
          "app"
        ],
        "description": "Get the global configuration for an application. Should be called during app statup.\n\nThis includes things like device and playback rules, classifications,\nsitemap and subscriptions.\n\nYou have the option to select specific configuration objects using the 'include'\nparameter, or if unspecified, getting all configuration.\n",
        "operationId": "getAppConfig"
      },
      "x-serviceId": "itvConfig"
    },
    "/ee-bt/eligibility": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "ee",
          "bt"
        ],
        "description": "Check whether or not a user is eligible for switching to Bt or EE offers.",
        "operationId": "checkEeBtEligibility"
      },
      "x-serviceId": "itvSubscription"
    },
    "/ee/msisdn": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "ee"
        ],
        "description": "Assigns a msisdn to a profile on ITV side.",
        "operationId": "assignMsisdn"
      },
      "x-serviceId": "itvEe"
    },
    "/ee/offers": {
      "post": {
        "tags": [
          "ee"
        ],
        "description": "Returns eligible partner specific offers for the querying partner for an EE MSISDN.\nThis call is supposed to be called after we have MSISDN accired.\nThis call should be followed by POST /ee/msisdn.\n",
        "operationId": "getEligibleOffers"
      },
      "x-serviceId": "eeOffers"
    },
    "/ee/pin": {
      "post": {
        "tags": [
          "ee"
        ],
        "description": "Validate PIN request created by calling POST /ee/pin This call is to validate MSISDN entered by a user not comming through EE network. This call should be called after PUT /ee/pin. This call should be followed by POST /ee/offers.",
        "operationId": "validatePinRequest"
      },
      "put": {
        "tags": [
          "ee"
        ],
        "description": "Creates a PIN request that will send an SMS to the given msisdn.\nThis call is to validate MSISDN entered by a user not comming through EE network.\nThis call should be followed by POST ee/pin.\n",
        "operationId": "createPinRequest"
      },
      "x-serviceId": "eeCredentials"
    },
    "/ee/plans": {
      "get": {
        "tags": [
          "ee"
        ],
        "description": "Returns all the plans available for EE flow including additional description data.",
        "operationId": "getPlansEE"
      },
      "x-serviceId": "itvEe"
    },
    "/ee/plans/{id}": {
      "get": {
        "tags": [
          "ee"
        ],
        "description": "Returns the plan description for EE flow including additional description data.",
        "operationId": "getPlanEE"
      },
      "x-serviceId": "itvEe"
    },
    "/ee/token/create": {
      "get": {
        "tags": [
          "ee"
        ],
        "description": "Returns a token for later calls to EE API. TTL is one hour. Recommended is FE refreshes this token before each call.",
        "operationId": "createToken"
      },
      "x-serviceId": "eeAuth"
    },
    "/items/{id}": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns the details of an item with the specified id.",
        "operationId": "getItem"
      },
      "x-serviceId": "item"
    },
    "/items/{id}/children": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns the List of child summary items under an item.\n\nIf the item is a Season then the children will be episodes and ordered by episode number.\n\nIf the item is a Show then the children will be Seasons and ordered by season number.\n\nReturns 404 if no children found.\n",
        "operationId": "getItemChildrenList"
      },
      "x-serviceId": "itemChildList"
    },
    "/items/{id}/related": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns the list of items related to the parent item.\n\nNote for now, due to the size of the list being unknown, only a single page will be returned.\n",
        "operationId": "getItemRelatedList"
      },
      "x-serviceId": "itemRelatedList"
    },
    "/items/{id}/videos": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Get the free / public video files associated with an item given maximum resolution,\ndevice type and one or more delivery types.\n\nReturns an array of video file objects which each include a url to a video.\n\nThe first entry in the array contains what is predicted to be the best match.\nThe remainder of the entries, if any, may contain resolutions below what was\nrequests. For example if you request HD-720 the response may also contain\nSD entries.\n\nIf you specify mul[...]",
        "operationId": "getPublicItemMediaFiles"
      },
      "x-serviceId": "media"
    },
    "/items/{itemId}/next": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Identical to GET /account/profile/items/{itemId}/next route but for users\nthat are not logged in i.e. this endpoint does not require authorisation\n",
        "operationId": "getAnonNextPlaybackItem"
      },
      "x-serviceId": "continueWatching"
    },
    "/itv/billinghistory/{platform}": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the list of billing records for specified payment platform.",
        "operationId": "getBillingHistory"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/cards/{platform}": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Get payment card details.",
        "operationId": "getCardDetails"
      },
      "put": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Change payment card details.",
        "operationId": "changeCardDetails"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/changeemail": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Change email address related to account/profile.\n\nThe expected token scope is Settings.\n",
        "operationId": "changeEmail"
      },
      "x-serviceId": "itvProfile"
    },
    "/itv/changemarketing": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Change marketing preferences related to account/profile.\n\nThe expected token scope is Settings.\n",
        "operationId": "changeMarketing"
      },
      "x-serviceId": "itvProfile"
    },
    "/itv/deleteaccount": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Delete account in compliance with GDPR.\n\nThe expected token scope is Settings.\n",
        "operationId": "deleteAccount"
      },
      "x-serviceId": "itvGdpr"
    },
    "/itv/entitlements/history": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the state of subscription for any payment platform.",
        "operationId": "getEntitlementsHistory"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/featureFlag/{feature}": {
      "get": {
        "tags": [
          "itv"
        ],
        "description": "Gets info whether or not a feature is enabled or disabled using a feature flag. Feature flags are set as a custom field within PM. It also supports custom feature flag data if needed. Such data can be return as well.",
        "operationId": "getFeatureFlag"
      },
      "x-serviceId": "itvConfig"
    },
    "/itv/items/downloadable": {
      "post": {
        "tags": [
          "content"
        ],
        "description": "Returns the details of an item with the specified id.",
        "operationId": "getItemDownloadables"
      },
      "x-serviceId": "itvItem"
    },
    "/itv/itemsummary/{externalId}": {
      "get": {
        "tags": [
          "itv"
        ],
        "description": "Redirects to corresponding Axis Item details page.",
        "operationId": "getItemItv"
      },
      "x-serviceId": "itvInfo"
    },
    "/itv/page": {
      "get": {
        "tags": [
          "app"
        ],
        "description": "Returns a page with the specified id.\n\nThis is a cut down version for low memory devices.123\n\nIf targeting the search page you must url encode the search term as a parameter\nusing the `q` key. For example if your browser path looks like `/search?q=the`\nthen what you pass to this endpoint would look like `/itv/page?path=/search%3Fq%3Dthe`.\n",
        "operationId": "getItvPage"
      },
      "x-serviceId": "itvPage"
    },
    "/itv/pinauthorization": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Provides authorization with parental control pin.\n\nReturns an array containing account token with Playback scope.\n\nRequires access token with Catalog scope.\n\nPin must be a 4-digit string\n",
        "operationId": "getAccountTokenWithPin"
      },
      "x-serviceId": "itvAuth"
    },
    "/itv/plan/{platform}": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Upgrades the plan for the current user.",
        "operationId": "upgradePlan"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/plans/{platform}": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the plans available for specified payment platform.",
        "operationId": "getPlansITV"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/profile": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the ITV profile object.",
        "operationId": "getProfileItv"
      },
      "put": {
        "security": [
          {
            "accountAuth": [
              "Settings"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Update ITV profile.\n\nThe expected token scope is Settings.\n",
        "operationId": "updateProfile"
      },
      "x-serviceId": "itvProfile"
    },
    "/itv/profiletoken": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the ITV profile token.",
        "operationId": "getItvProfileToken"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/purchase/{platform}": {
      "delete": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Cancel a plan subscription.\n\nA cancelled subscription will continue to be valid until the subscription\nexpiry date or next renewal date.\n",
        "operationId": "cancelSubscriptionItv"
      },
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the details of current subscription for specified payment platform.",
        "operationId": "getCurrentSubscription"
      },
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Confirms purchase and returns the details of purchased subscription for specified payment platform.",
        "operationId": "confirmPurchase"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/save-offer": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Checks the provided coupon id for a user. Only Stripe platform is currently supported.",
        "operationId": "getSaveOffer"
      },
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Activates the discount for a user. Only Stripe platform is currently supported.",
        "operationId": "activateSaveOffer"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/subscriptionstate": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns the state of subscription for any payment platform.",
        "operationId": "getSubscriptionState"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/upcominginvoice": {
      "get": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Returns an upcoming invoice",
        "operationId": "getUpcomingInvoice"
      },
      "x-serviceId": "itvSubscription"
    },
    "/itv/voucher/{platform}": {
      "post": {
        "security": [
          {
            "accountAuth": [
              "Catalog"
            ]
          }
        ],
        "tags": [
          "itv"
        ],
        "description": "Validates the coupon/voucher for specified payment platform.",
        "operationId": "checkVoucher"
      },
      "x-serviceId": "itvSubscription"
    },
    "/lists": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns an array of item lists with their first page of content resolved.",
        "operationId": "getLists"
      },
      "x-serviceId": "list"
    },
    "/lists/{id}": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns a list of items under the specified item list",
        "operationId": "getList"
      },
      "x-serviceId": "list"
    },
    "/page": {
      "get": {
        "tags": [
          "app"
        ],
        "description": "Returns a page with the specified id.\n\nIf targeting the search page you must url encode the search term as a parameter\nusing the `q` key. For example if your browser path looks like `/search?q=the`\nthen what you pass to this endpoint would look like `/page?path=/search%3Fq%3Dthe`.\n",
        "operationId": "getPage"
      },
      "x-serviceId": "page"
    },
    "/plans/{id}": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns the details of a Plan with the specified id.",
        "operationId": "getPlan"
      },
      "x-serviceId": "subscription"
    },
    "/register": {
      "post": {
        "tags": [
          "registration"
        ],
        "description": "Register a new user, creating them an account.\n\nRegistration, when successful, will return an array of access tokens so the user is\nimmediately signed in.\n\nIt returns Catalog and Commerce scoped tokens for both Account and Profile.\nThe Commerce ones are intended to allow the purchase of a subscription plan\nin the step after registration, without the user being prompted to enter\ntheir username and password again.\n\nAn email will also be sent with a link they need [...]",
        "operationId": "register"
      },
      "x-serviceId": "itvRegistration"
    },
    "/request-password-reset": {
      "post": {
        "tags": [
          "support"
        ],
        "description": "Request the password of an account's primary profile be reset.\n\nShould be called when a user has forgotten their password.\n\nThis will send an email with a password reset link to the email address of the\nprimary profile of an account.\n\nThe link, once clicked, should take the user to the \"reset-password\" page of the\nwebsite. Here they will enter their new password and submit to the /reset-password\nendpoint here, along with the password reset token provided in the[...]",
        "operationId": "forgotPassword"
      },
      "x-serviceId": "itvPassword"
    },
    "/reset-password": {
      "post": {
        "tags": [
          "support"
        ],
        "description": "When a user requests to reset their password via the /request-password-reset endpoint, an\nemail is sent to the email address of the primary profile of the account. This email contains a link\nwith a reset token as query parameter. The link should take the user to the \"reset-password\"\npage of the website.\n\nFrom the reset-password page a user should enter the new password they wish to use.\nIt should then be submitted to this endpoint,\nalong with the reset token from[...]",
        "operationId": "resetPassword"
      },
      "x-serviceId": "itvPassword"
    },
    "/samsung-preview": {
      "get": {
        "tags": [
          "itv"
        ],
        "description": "Returns public preview for Samsung based on the page '/samsung-preview' configured in PresentationManager.\nThere is a hard limit of max 40 items to be returned. It splits evenly items count into the page rows, remaining items are added into the first row.\n",
        "operationId": "getPublicPreview"
      },
      "x-serviceId": "itvSamsung"
    },
    "/schedules": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Returns schedules for a defined set of channels over a requested period.\n\nSchedules are requested in hour blocks and returned grouped by the channel\nthey belong to.\n\nFor example, to load 12 hours of schedules for channels `4343` and `5234`,\non 21/2/2017 starting from 08:00.\n\n```\nchannels=4343,5234\ndate=2017-02-21\nhour=8\nduration=12\n```\n\nPlease remember that `date` and `hour` combined represent a normal datetime,\nso they should be converted to UTC on the cl[...]",
        "operationId": "getSchedules"
      },
      "x-serviceId": "schedule"
    },
    "/search": {
      "get": {
        "tags": [
          "content"
        ],
        "description": "Search the catalog of items and people.",
        "operationId": "search"
      },
      "x-serviceId": "search"
    },
    "/verify-email": {
      "post": {
        "security": [
          {
            "verifyEmailAuth": []
          }
        ],
        "tags": [
          "support"
        ],
        "description": "When an account is created an email is sent to the email address of the new account.\nThis contains a link, which once clicked, verifies the email address of the account is correct.\n\nThe link contains a token as a query parameter which should be passed as the authorization\nbearer token to this endpoint to complete email verification.\n\nThe token has en expiry, so if the link is not clicked before it expires, the account holder\nmay need to request a new verification e[...]",
        "operationId": "verifyEmail"
      },
      "x-serviceId": "support"
    }
  },
  "securityDefinitions": {
    "accountAuth": {
      "description": "Account JWT token",
      "flow": "password",
      "scopes": {
        "Catalog": "Access all read only content",
        "Commerce": "Perform account level transactions",
        "Playback": "Allow playback of restricted content",
        "Settings": "Modify account settings"
      },
      "tokenUrl": "/account/authorization",
      "type": "oauth2"
    },
    "profileAuth": {
      "description": "Profile JWT token",
      "flow": "password",
      "scopes": {
        "Catalog": "Modify profile preferences and activity (bookmarks, watch list)"
      },
      "tokenUrl": "/account/profile/authorization",
      "type": "oauth2"
    },
    "resetPasswordAuth": {
      "in": "header",
      "name": "authorization",
      "type": "apiKey"
    },
    "verifyEmailAuth": {
      "in": "header",
      "name": "authorization",
      "type": "apiKey"
    }
  },
  "x-components": {
  }
}