{
  "swagger": "2.0",
  "info": {
    "contact": {
      "url": "https://developer.vimeo.com/help",
      "x-twitter": "vimeo"
    },
    "title": "Vimeo",
    "version": "3.4",
    "x-apisguru-categories": [
      "entertainment"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_twitter.com_vimeo_profile_image.jpeg"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.7.31"
        },
        "format": "openapi",
        "url": "https://raw.githubusercontent.com/vimeo/openapi/master/api.yaml",
        "version": "3.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "vimeo.com",
    "x-datafire": {
      "name": "vimeo",
      "type": "openapi"
    }
  },
  "host": "api.vimeo.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/": {
      "get": {
        "tags": [
          "API Information"
        ],
        "operationId": "get_endpoints",
        "summary": "Get an API specification"
      }
    },
    "/categories": {
      "get": {
        "tags": [
          "Categories\\Essentials"
        ],
        "description": "This method gets all existing categories.",
        "operationId": "get_categories",
        "summary": "Get all categories"
      }
    },
    "/categories/{category}": {
      "get": {
        "tags": [
          "Categories\\Essentials"
        ],
        "operationId": "get_category",
        "summary": "Get a specific category"
      }
    },
    "/categories/{category}/channels": {
      "get": {
        "tags": [
          "Categories\\Channels"
        ],
        "operationId": "get_category_channels",
        "summary": "Get all the channels in a category"
      }
    },
    "/categories/{category}/groups": {
      "get": {
        "tags": [
          "Categories\\Groups"
        ],
        "operationId": "get_category_groups",
        "summary": "Get all the groups in a category"
      }
    },
    "/categories/{category}/videos": {
      "get": {
        "tags": [
          "Categories\\Videos"
        ],
        "operationId": "get_category_videos",
        "summary": "Get all the videos in a category"
      }
    },
    "/categories/{category}/videos/{video_id}": {
      "get": {
        "tags": [
          "Categories\\Videos"
        ],
        "operationId": "check_category_for_video",
        "summary": "Check for a video in a category"
      }
    },
    "/channels": {
      "get": {
        "tags": [
          "Channels\\Essentials"
        ],
        "operationId": "get_channels",
        "summary": "Get all channels"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Channels\\Essentials"
        ],
        "description": "This method creates a new channel.",
        "operationId": "create_channel",
        "summary": "Create a channel"
      }
    },
    "/channels/{channel_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Channels\\Essentials"
        ],
        "operationId": "delete_channel",
        "summary": "Delete a channel"
      },
      "get": {
        "tags": [
          "Channels\\Essentials"
        ],
        "operationId": "get_channel",
        "summary": "Get a specific channel"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Essentials"
        ],
        "description": "This method edits the specified channel.",
        "operationId": "edit_channel",
        "summary": "Edit a channel"
      }
    },
    "/channels/{channel_id}/categories": {
      "get": {
        "tags": [
          "Channels\\Categories"
        ],
        "description": "This method gets all the categories in the specified channel.",
        "operationId": "get_channel_categories",
        "summary": "Get all the categories in a channel"
      },
      "put": {
        "tags": [
          "Channels\\Categories"
        ],
        "description": "This method adds multiple categories to the specified channel.",
        "operationId": "add_channel_categories",
        "summary": "Add a list of categories to a channel"
      }
    },
    "/channels/{channel_id}/categories/{category}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Categories"
        ],
        "description": "This method removes a single category from the specified channel.",
        "operationId": "delete_channel_category",
        "summary": "Remove a category from a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Categories"
        ],
        "description": "This method adds a channel to a category.",
        "operationId": "categorize_channel",
        "summary": "Categorize a channel"
      }
    },
    "/channels/{channel_id}/moderators": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "remove_channel_moderators",
        "summary": "Remove a list of channel moderators"
      },
      "get": {
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "get_channel_moderators",
        "summary": "Get all the moderators in a channel"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "replace_channel_moderators",
        "summary": "Replace the moderators of a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "add_channel_moderators",
        "summary": "Add a list of channel moderators"
      }
    },
    "/channels/{channel_id}/moderators/{user_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "remove_channel_moderator",
        "summary": "Remove a specific channel moderator"
      },
      "get": {
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "get_channel_moderator",
        "summary": "Get a specific channel moderator"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Moderators"
        ],
        "operationId": "add_channel_moderator",
        "summary": "Add a specific channel moderator"
      }
    },
    "/channels/{channel_id}/privacy/users": {
      "get": {
        "tags": [
          "Channels\\Private channel members"
        ],
        "description": "This method gets all the users who have access to the specified private channel.",
        "operationId": "get_channel_privacy_users",
        "summary": "Get all the users who can view a private channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Private channel members"
        ],
        "description": "This method gives multiple users access to the specified private channel.",
        "operationId": "set_channel_privacy_users",
        "summary": "Permit a list of users to view a private channel"
      }
    },
    "/channels/{channel_id}/privacy/users/{user_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Private channel members"
        ],
        "description": "This method prevents a single user from being able to access the specified private channel.",
        "operationId": "delete_channel_privacy_user",
        "summary": "Restrict a user from viewing a private channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Private channel members"
        ],
        "description": "This method gives a single user access to the specified private channel.",
        "operationId": "set_channel_privacy_user",
        "summary": "Permit a specific user to view a private channel"
      }
    },
    "/channels/{channel_id}/tags": {
      "get": {
        "tags": [
          "Channels\\Tags"
        ],
        "description": "This method gets all the tags that have been added to the specified channel.",
        "operationId": "get_channel_tags",
        "summary": "Get all the tags that have been added to a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Tags"
        ],
        "description": "This method adds multiple tags to the specified channel.",
        "operationId": "add_tags_to_channel",
        "summary": "Add a list of tags to a channel"
      }
    },
    "/channels/{channel_id}/tags/{word}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Tags"
        ],
        "description": "This method removes a single tag from the specified channel.",
        "operationId": "delete_tag_from_channel",
        "summary": "Remove a tag from a channel"
      },
      "get": {
        "tags": [
          "Channels\\Tags"
        ],
        "description": "This method determines whether a specific tag has been added to the channel in question.",
        "operationId": "check_if_channel_has_tag",
        "summary": "Check if a tag has been added to a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Tags"
        ],
        "description": "This method adds a single tag to the specified channel.",
        "operationId": "add_channel_tag",
        "summary": "Add a specific tag to a channel"
      }
    },
    "/channels/{channel_id}/users": {
      "get": {
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "get_channel_subscribers",
        "summary": "Get all the followers of a channel"
      }
    },
    "/channels/{channel_id}/videos": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "remove_videos_from_channel",
        "summary": "Remove a list of videos from a channel"
      },
      "get": {
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "get_channel_videos",
        "summary": "Get all the videos in a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "add_videos_to_channel",
        "summary": "Add a list of videos to a channel"
      }
    },
    "/channels/{channel_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "delete_video_from_channel",
        "summary": "Remove a specific video from a channel"
      },
      "get": {
        "tags": [
          "Channels\\Videos"
        ],
        "description": "This method returns a specific video in a channel. You can use it to determine whether the video is in the channel.",
        "operationId": "get_channel_video",
        "summary": "Get a specific video in a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "add_video_to_channel",
        "summary": "Add a specific video to a channel"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/comments": {
      "get": {
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "get_comments_alt1",
        "summary": "Get all the comments on a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "create_comment_alt1",
        "summary": "Add a comment to a video"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/credits": {
      "get": {
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "get_video_credits_alt1",
        "summary": "Get all the credited users in a video"
      },
      "post": {
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "add_video_credit_alt1",
        "summary": "Credit a user in a video"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/likes": {
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "get_video_likes_alt1",
        "summary": "Get all the users who have liked a video"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/pictures": {
      "get": {
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "get_video_thumbnails_alt1",
        "summary": "Get all the thumbnails of a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "create_video_thumbnail_alt1",
        "summary": "Add a video thumbnail"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/privacy/users": {
      "get": {
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "operationId": "get_video_privacy_users_alt1",
        "summary": "Get all the users who can view a user's private videos by default"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "description": "The body of this request should follow our\n[batch request format](https://developer.vimeo.com/api/common-formats#batch-requests). Each object must contain\na single `URI` field, and the value of this field must be the URI of the user who can view this video.",
        "operationId": "add_video_privacy_users_alt1",
        "summary": "Permit a list of users to view a private video"
      }
    },
    "/channels/{channel_id}/videos/{video_id}/texttracks": {
      "get": {
        "tags": [
          "Videos\\Text Tracks"
        ],
        "operationId": "get_text_tracks_alt1",
        "summary": "Get all the text tracks of a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Text Tracks"
        ],
        "description": "For additional information, see our [text track upload guide](https://developer.vimeo.com/api/upload/texttracks).",
        "operationId": "create_text_track_alt1",
        "summary": "Add a text track to a video"
      }
    },
    "/contentratings": {
      "get": {
        "tags": [
          "Videos\\Content Ratings"
        ],
        "operationId": "get_content_ratings",
        "summary": "Get all content ratings"
      }
    },
    "/creativecommons": {
      "get": {
        "tags": [
          "Videos\\Creative Commons"
        ],
        "operationId": "get_cc_licenses",
        "summary": "Get all Creative Commons licenses"
      }
    },
    "/groups": {
      "get": {
        "tags": [
          "Groups\\Essentials"
        ],
        "operationId": "get_groups",
        "summary": "Get all groups"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Groups\\Essentials"
        ],
        "operationId": "create_group",
        "summary": "Create a group"
      }
    },
    "/groups/{group_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Groups\\Essentials"
        ],
        "operationId": "delete_group",
        "summary": "Delete a group"
      },
      "get": {
        "tags": [
          "Groups\\Essentials"
        ],
        "operationId": "get_group",
        "summary": "Get a specific group"
      }
    },
    "/groups/{group_id}/users": {
      "get": {
        "tags": [
          "Groups\\Users"
        ],
        "operationId": "get_group_members",
        "summary": "Get all the members of a group"
      }
    },
    "/groups/{group_id}/videos": {
      "get": {
        "tags": [
          "Groups\\Videos"
        ],
        "operationId": "get_group_videos",
        "summary": "Get all the videos in a group"
      }
    },
    "/groups/{group_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Groups\\Videos"
        ],
        "operationId": "delete_video_from_group",
        "summary": "Remove a video from a group"
      },
      "get": {
        "tags": [
          "Groups\\Videos"
        ],
        "description": "Check if a group has a video.",
        "operationId": "get_group_video",
        "summary": "Get a specific video in a group"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Groups\\Videos"
        ],
        "operationId": "add_video_to_group",
        "summary": "Add a video to a group"
      }
    },
    "/languages": {
      "get": {
        "tags": [
          "Videos\\Languages"
        ],
        "operationId": "get_languages",
        "summary": "Get all languages"
      }
    },
    "/me": {
      "get": {
        "tags": [
          "Users\\Essentials"
        ],
        "operationId": "get_user_alt1",
        "summary": "Get a user"
      },
      "patch": {
        "tags": [
          "Users\\Essentials"
        ],
        "operationId": "edit_user_alt1",
        "summary": "Edit a user"
      }
    },
    "/me/albums": {
      "get": {
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "get_albums_alt1",
        "summary": "Get all the albums that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "create_album_alt1",
        "summary": "Create an album"
      }
    },
    "/me/albums/{album_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "delete_album_alt1",
        "summary": "Delete an album"
      },
      "get": {
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "get_album_alt1",
        "summary": "Get a specific album"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "edit_album_alt1",
        "summary": "Edit an album"
      }
    },
    "/me/albums/{album_id}/videos": {
      "get": {
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "get_album_videos_alt1",
        "summary": "Get all the videos in an album"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "description": "This method replaces all the existing videos in an album with one or more videos.",
        "operationId": "replace_videos_in_album_alt1",
        "summary": "Replace all the videos in an album"
      }
    },
    "/me/albums/{album_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "remove_video_from_album_alt1",
        "summary": "Remove a video from an album"
      },
      "get": {
        "tags": [
          "Albums\\Album videos"
        ],
        "description": "This method gets a single video from an album. You can use this method to determine whether the album contains the specified video.",
        "operationId": "get_album_video_alt1",
        "summary": "Get a specific video in an album"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "add_video_to_album_alt1",
        "summary": "Add a specific video to an album"
      }
    },
    "/me/albums/{album_id}/videos/{video_id}/set_album_thumbnail": {
      "post": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "set_video_as_album_thumbnail_alt1",
        "summary": "Set a video as the album thumbnail"
      }
    },
    "/me/appearances": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "get_appearances_alt1",
        "summary": "Get all the videos in which a user appears"
      }
    },
    "/me/categories": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "get_category_subscriptions_alt1",
        "summary": "Get all the categories that a user follows"
      }
    },
    "/me/categories/{category}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "unsubscribe_from_category_alt1",
        "summary": "Unsubscribe a user from a category"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "check_if_user_subscribed_to_category_alt1",
        "summary": "Check if a user follows a category"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "subscribe_to_category_alt1",
        "summary": "Subscribe a user to a single category"
      }
    },
    "/me/channels": {
      "get": {
        "tags": [
          "Channels\\Essentials"
        ],
        "operationId": "get_channel_subscriptions_alt1",
        "summary": "Get all the channels to which a user subscribes"
      }
    },
    "/me/channels/{channel_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "unsubscribe_from_channel_alt1",
        "summary": "Unsubscribe a user from a specific channel"
      },
      "get": {
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "check_if_user_subscribed_to_channel_alt1",
        "summary": "Check if a user follows a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "subscribe_to_channel_alt1",
        "summary": "Subscribe a user to a specific channel"
      }
    },
    "/me/customlogos": {
      "get": {
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "get_custom_logos_alt1",
        "summary": "Get all the custom logos that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "create_custom_logo_alt1",
        "summary": "Add a custom logo"
      }
    },
    "/me/customlogos/{logo_id}": {
      "get": {
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "get_custom_logo_alt1",
        "summary": "Get a specific custom logo"
      }
    },
    "/me/feed": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Users\\Feed"
        ],
        "operationId": "get_feed_alt1",
        "summary": "Get all videos in a user's feed"
      }
    },
    "/me/followers": {
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "get_followers_alt1",
        "summary": "Get all the followers of a user"
      }
    },
    "/me/following": {
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "get_user_following_alt1",
        "summary": "Get all the users that a user is following"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "follow_users_alt1",
        "summary": "Follow a list of users"
      }
    },
    "/me/following/{follow_user_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "unfollow_user_alt1",
        "summary": "Unfollow a user"
      },
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "check_if_user_is_following_alt1",
        "summary": "Check if a user is following another user"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "follow_user_alt1",
        "summary": "Follow a specific user"
      }
    },
    "/me/groups": {
      "get": {
        "tags": [
          "Groups\\Users"
        ],
        "operationId": "get_user_groups_alt1",
        "summary": "Get all the groups that a user has joined"
      }
    },
    "/me/groups/{group_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Groups\\Subscription"
        ],
        "operationId": "leave_group_alt1",
        "summary": "Remove a user from a group"
      },
      "get": {
        "tags": [
          "Groups\\Users"
        ],
        "operationId": "check_if_user_joined_group_alt1",
        "summary": "Check if a user has joined a group"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Groups\\Subscription"
        ],
        "operationId": "join_group_alt1",
        "summary": "Add a user to a group"
      }
    },
    "/me/likes": {
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "get_likes_alt1",
        "summary": "Get all the videos that a user has liked"
      }
    },
    "/me/likes/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "unlike_video_alt1",
        "summary": "Cause a user to unlike a video"
      },
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "check_if_user_liked_video_alt1",
        "summary": "Check if a user has liked a video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "like_video_alt1",
        "summary": "Cause a user to like a video"
      }
    },
    "/me/ondemand/pages": {
      "get": {
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "get_user_vods_alt1",
        "summary": "Get all the On Demand pages of a user"
      },
      "post": {
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "create_vod_alt1",
        "summary": "Create an On Demand page"
      }
    },
    "/me/ondemand/purchases": {
      "get": {
        "security": [
          {
            "oauth2": [
              "purchased"
            ]
          }
        ],
        "tags": [
          "On Demand\\Purchases and Rentals"
        ],
        "operationId": "get_vod_purchases",
        "summary": "Get all the On Demand purchases and rentals that a user has made"
      }
    },
    "/me/ondemand/purchases/{ondemand_id}": {
      "get": {
        "security": [
          {
            "oauth2": [
              "purchased"
            ]
          }
        ],
        "tags": [
          "On Demand\\Purchases and Rentals"
        ],
        "operationId": "check_if_vod_was_purchased_alt1",
        "summary": "Check if a user has made a purchase or rental from an On Demand page"
      }
    },
    "/me/pictures": {
      "get": {
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "get_pictures_alt1",
        "summary": "Get all the pictures that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "create_picture_alt1",
        "summary": "Add a user picture"
      }
    },
    "/me/pictures/{portraitset_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "delete_picture_alt1",
        "summary": "Delete a user picture"
      },
      "get": {
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "get_picture_alt1",
        "summary": "Get a specific user picture"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "edit_picture_alt1",
        "summary": "Edit a user picture"
      }
    },
    "/me/portfolios": {
      "get": {
        "tags": [
          "Portfolios\\Essentials"
        ],
        "operationId": "get_portfolios_alt1",
        "summary": "Get all the portfolios that belong to a user"
      }
    },
    "/me/portfolios/{portfolio_id}": {
      "get": {
        "tags": [
          "Portfolios\\Essentials"
        ],
        "operationId": "get_portfolio_alt1",
        "summary": "Get a specific portfolio"
      }
    },
    "/me/portfolios/{portfolio_id}/videos": {
      "get": {
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "get_portfolio_videos_alt1",
        "summary": "Get all the videos in a portfolio"
      }
    },
    "/me/portfolios/{portfolio_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "delete_video_from_portfolio_alt1",
        "summary": "Remove a video from a portfolio"
      },
      "get": {
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "get_portfolio_video_alt1",
        "summary": "Get a specific video in a portfolio"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "add_video_to_portfolio_alt1",
        "summary": "Add a video to a portfolio"
      }
    },
    "/me/presets": {
      "get": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "get_embed_presets_alt1",
        "summary": "Get all the embed presets that a user has created"
      }
    },
    "/me/presets/{preset_id}": {
      "get": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "get_embed_preset_alt1",
        "summary": "Get a specific embed preset"
      },
      "patch": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "edit_embed_preset_alt1",
        "summary": "Edit an embed preset"
      }
    },
    "/me/presets/{preset_id}/videos": {
      "get": {
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "get_embed_preset_videos_alt1",
        "summary": "Get all the videos that have been added to an embed preset"
      }
    },
    "/me/projects": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method gets all the projects that belong to the specified user.",
        "operationId": "get_projects_alt1",
        "summary": "Get all the projects that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method creates a new project for the specified user.",
        "operationId": "create_project_alt1",
        "summary": "Create a project"
      }
    },
    "/me/projects/{project_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method deletes a project and optionally also the videos that it contains.",
        "operationId": "delete_project_alt1",
        "summary": "Delete a project"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method gets a single project that belongs to the specified user.",
        "operationId": "get_project_alt1",
        "summary": "Get a specific project"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method edits an existing project.",
        "operationId": "edit_project_alt1",
        "summary": "Edit a project"
      }
    },
    "/me/projects/{project_id}/videos": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method removed multiple videos from the specified project.",
        "operationId": "remove_videos_from_project_alt1",
        "summary": "Remove a list of videos from a project"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method gets all the videos that belong to the specified project.",
        "operationId": "get_project_videos_alt1",
        "summary": "Get all the videos in a project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method adds multiple videos to the specified project.",
        "operationId": "add_videos_to_project_alt1",
        "summary": "Add a list of videos to a project"
      }
    },
    "/me/projects/{project_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method removes a single video from the specified project.",
        "operationId": "remove_video_from_project_alt1",
        "summary": "Remove a specific video from a project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method adds a single video to the specified project.",
        "operationId": "add_video_to_project_alt1",
        "summary": "Add a specific video to a project"
      }
    },
    "/me/videos": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "get_videos_alt1",
        "summary": "Get all the videos that a user has uploaded"
      },
      "post": {
        "tags": [
          "Videos\\Upload"
        ],
        "description": "Begin the video upload process. For more information, see our [upload documentation](https://developer.vimeo.com/api/upload/videos).",
        "operationId": "upload_video_alt1",
        "summary": "Upload a video"
      }
    },
    "/me/videos/{video_id}": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "check_if_user_owns_video_alt1",
        "summary": "Check if a user owns a video"
      }
    },
    "/me/watched/videos": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Users\\Watch History"
        ],
        "operationId": "delete_watch_history",
        "summary": "Delete a user's watch history"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Users\\Watch History"
        ],
        "operationId": "get_watch_history",
        "summary": "Get all the videos that a user has watched"
      }
    },
    "/me/watched/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Users\\Watch History"
        ],
        "operationId": "delete_from_watch_history",
        "summary": "Delete a specific video from a user's watch history"
      }
    },
    "/me/watchlater": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "get_watch_later_queue_alt1",
        "summary": "Get all the videos in a user's Watch Later queue"
      }
    },
    "/me/watchlater/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "delete_video_from_watch_later_alt1",
        "summary": "Remove a video from a user's Watch Later queue"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "check_watch_later_queue_alt1",
        "summary": "Check if a user has added a specific video to their Watch Later queue"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "add_video_to_watch_later_alt1",
        "summary": "Add a video to a user's Watch Later queue"
      }
    },
    "/oauth/access_token": {
      "post": {
        "tags": [
          "Authentication Extras\\Essentials"
        ],
        "operationId": "exchange_auth_code",
        "summary": "Exchange an authorization code for an access token"
      }
    },
    "/oauth/authorize/client": {
      "post": {
        "tags": [
          "Authentication Extras\\Essentials"
        ],
        "description": "For information on utilizing OAuth client authorization, see our\n[authentication](/api/authentication#generate-unauthenticated-tokens) documentation or the\n[Client Credentials Grant](https://tools.ietf.org/html/draft-ietf-oauth-v2-31#section-4.4) section of the\n[OAuth spec](https://tools.ietf.org/html/draft-ietf-oauth-v2-31.",
        "operationId": "client_auth",
        "summary": "Authorize a client with OAuth"
      }
    },
    "/oauth/authorize/vimeo_oauth1": {
      "post": {
        "tags": [
          "Authentication Extras\\Essentials"
        ],
        "operationId": "convert_access_token",
        "summary": "Convert OAuth 1 access tokens to OAuth 2 access tokens"
      }
    },
    "/oauth/verify": {
      "get": {
        "tags": [
          "Authentication Extras\\Essentials"
        ],
        "operationId": "verify_token",
        "summary": "Verify an OAuth 2 token"
      }
    },
    "/ondemand/genres": {
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "get_vod_genres",
        "summary": "Get all On Demand genres"
      }
    },
    "/ondemand/genres/{genre_id}": {
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "get_vod_genre",
        "summary": "Get a specific On Demand genre"
      }
    },
    "/ondemand/genres/{genre_id}/pages": {
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "get_genre_vods",
        "summary": "Get all the On Demand pages in a genre"
      }
    },
    "/ondemand/genres/{genre_id}/pages/{ondemand_id}": {
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "description": "Check whether a genre contains an On Demand page.",
        "operationId": "get_genre_vod",
        "summary": "Get a specific On Demand page in a genre"
      }
    },
    "/ondemand/pages/{ondemand_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "delete_vod_draft",
        "summary": "Delete a draft of an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "get_vod",
        "summary": "Get a specific On Demand page"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Essentials"
        ],
        "description": "Enable preorders or publish the page.",
        "operationId": "edit_vod",
        "summary": "Edit an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/backgrounds": {
      "get": {
        "tags": [
          "On Demand\\Backgrounds"
        ],
        "operationId": "get_vod_backgrounds",
        "summary": "Get all the backgrounds of an On Demand page"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "On Demand\\Backgrounds"
        ],
        "operationId": "create_vod_background",
        "summary": "Add a background to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/backgrounds/{background_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Backgrounds"
        ],
        "operationId": "delete_vod_background",
        "summary": "Remove a background from an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Backgrounds"
        ],
        "operationId": "get_vod_background",
        "summary": "Get a specific background of an On Demand page"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Backgrounds"
        ],
        "operationId": "edit_vod_background",
        "summary": "Edit a background of an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/genres": {
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "get_vod_genres_by_ondemand_id",
        "summary": "Get all the genres of an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/genres/{genre_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "delete_vod_genre",
        "summary": "Remove a genre from an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "get_vod_genre_by_ondemand_id",
        "summary": "Check whether an On Demand page belongs to a genre"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Genres"
        ],
        "operationId": "add_vod_genre",
        "summary": "Add a genre to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/likes": {
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "description": "This method gets all the users who have liked a particular video on an On Demand page.",
        "operationId": "get_vod_likes",
        "summary": "Get all the users who have liked a video on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/pictures": {
      "get": {
        "tags": [
          "On Demand\\Posters"
        ],
        "operationId": "get_vod_posters",
        "summary": "Get all the posters of an On Demand page"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "On Demand\\Posters"
        ],
        "operationId": "add_vod_poster",
        "summary": "Add a poster to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/pictures/{poster_id}": {
      "get": {
        "tags": [
          "On Demand\\Posters"
        ],
        "operationId": "get_vod_poster",
        "summary": "Get a specific poster of an On Demand page"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Posters"
        ],
        "operationId": "edit_vod_poster",
        "summary": "Edit a poster of an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/promotions": {
      "get": {
        "security": [
          {
            "oauth2": [
              "promo_codes"
            ]
          }
        ],
        "tags": [
          "On Demand\\Promotions"
        ],
        "operationId": "get_vod_promotions",
        "summary": "Get all the promotions on an On Demand page"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "promo_codes",
              "create"
            ]
          }
        ],
        "tags": [
          "On Demand\\Promotions"
        ],
        "operationId": "create_vod_promotion",
        "summary": "Add a promotion to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/promotions/{promotion_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "promo_codes",
              "delete"
            ]
          }
        ],
        "tags": [
          "On Demand\\Promotions"
        ],
        "operationId": "delete_vod_promotion",
        "summary": "Remove a promotion from an On Demand page"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "promo_codes"
            ]
          }
        ],
        "tags": [
          "On Demand\\Promotions"
        ],
        "operationId": "get_vod_promotion",
        "summary": "Get a specific promotion on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/promotions/{promotion_id}/codes": {
      "get": {
        "security": [
          {
            "oauth2": [
              "promo_codes"
            ]
          }
        ],
        "tags": [
          "On Demand\\Promotions"
        ],
        "operationId": "get_vod_promotion_codes",
        "summary": "Get all the codes of a promotion on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/regions": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "delete_vod_regions",
        "summary": "Remove a list of regions from an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "get_vod_regions",
        "summary": "Get all the regions of an On Demand page"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "set_vod_regions",
        "summary": "Add a list of regions to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/regions/{country}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "delete_vod_region",
        "summary": "Remove a specific region from an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Regions"
        ],
        "description": "Checks whether an On Demand page belongs to a region.",
        "operationId": "get_vod_region",
        "summary": "Get a specific region of an On Demand page"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "add_vod_region",
        "summary": "Add a specific region to an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/seasons": {
      "get": {
        "tags": [
          "On Demand\\Seasons"
        ],
        "operationId": "get_vod_seasons",
        "summary": "Get all the seasons on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/seasons/{season_id}": {
      "get": {
        "tags": [
          "On Demand\\Seasons"
        ],
        "operationId": "get_vod_season",
        "summary": "Get a specific season on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/seasons/{season_id}/videos": {
      "get": {
        "tags": [
          "On Demand\\Seasons"
        ],
        "operationId": "get_vod_season_videos",
        "summary": "Get all the videos in a season on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/videos": {
      "get": {
        "tags": [
          "On Demand\\Videos"
        ],
        "operationId": "get_vod_videos",
        "summary": "Get all the videos on an On Demand page"
      }
    },
    "/ondemand/pages/{ondemand_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Videos"
        ],
        "operationId": "delete_video_from_vod",
        "summary": "Remove a video from an On Demand page"
      },
      "get": {
        "tags": [
          "On Demand\\Videos"
        ],
        "operationId": "get_vod_video",
        "summary": "Get a specific video on an On Demand page"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "On Demand\\Videos"
        ],
        "operationId": "add_video_to_vod",
        "summary": "Add a video to an On Demand page"
      }
    },
    "/ondemand/regions": {
      "get": {
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "get_regions",
        "summary": "Get all the On Demand regions"
      }
    },
    "/ondemand/regions/{country}": {
      "get": {
        "tags": [
          "On Demand\\Regions"
        ],
        "operationId": "get_region",
        "summary": "Get a specific On Demand region"
      }
    },
    "/tags/{word}": {
      "get": {
        "tags": [
          "Tags\\Essentials"
        ],
        "operationId": "get_tag",
        "summary": "Get a specific tag"
      }
    },
    "/tags/{word}/videos": {
      "get": {
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "get_videos_with_tag",
        "summary": "Get all the videos with a specific tag"
      }
    },
    "/tokens": {
      "delete": {
        "tags": [
          "Authentication Extras\\Essentials"
        ],
        "description": "This method enables an app to notify the API that it is done with a token and that the token can be discarded.",
        "operationId": "delete_token",
        "summary": "Revoke the current access token"
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users\\Internal"
        ],
        "operationId": "search_users",
        "summary": "Search for users"
      }
    },
    "/users/{user_id}": {
      "get": {
        "tags": [
          "Users\\Essentials"
        ],
        "operationId": "get_user",
        "summary": "Get a user"
      },
      "patch": {
        "tags": [
          "Users\\Essentials"
        ],
        "operationId": "edit_user",
        "summary": "Edit a user"
      }
    },
    "/users/{user_id}/albums": {
      "get": {
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "get_albums",
        "summary": "Get all the albums that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "create_album",
        "summary": "Create an album"
      }
    },
    "/users/{user_id}/albums/{album_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "delete_album",
        "summary": "Delete an album"
      },
      "get": {
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "get_album",
        "summary": "Get a specific album"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Essentials"
        ],
        "operationId": "edit_album",
        "summary": "Edit an album"
      }
    },
    "/users/{user_id}/albums/{album_id}/custom_thumbnails": {
      "get": {
        "tags": [
          "Albums\\Custom album thumbnails"
        ],
        "operationId": "get_album_custom_thumbs",
        "summary": "Get all the custom upload thumbnails of an album"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album thumbnails"
        ],
        "operationId": "create_album_custom_thumb",
        "summary": "Add a custom uploaded thumbnail"
      }
    },
    "/users/{user_id}/albums/{album_id}/custom_thumbnails/{thumbnail_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album thumbnails"
        ],
        "description": "This method removes a custom uploaded thumbnail from the specified album.",
        "operationId": "delete_album_custom_thumbnail",
        "summary": "Remove a custom uploaded album thumbnail"
      },
      "get": {
        "tags": [
          "Albums\\Custom album thumbnails"
        ],
        "operationId": "get_album_custom_thumbnail",
        "summary": "Get a specific custom uploaded album thumbnail"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album thumbnails"
        ],
        "operationId": "replace_album_custom_thumb",
        "summary": "Replace a custom uploaded album thumbnail"
      }
    },
    "/users/{user_id}/albums/{album_id}/logos": {
      "get": {
        "tags": [
          "Albums\\Custom album logos"
        ],
        "operationId": "get_album_logos",
        "summary": "Get all the custom logos of an album"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album logos"
        ],
        "operationId": "create_album_logo",
        "summary": "Add a custom album logo"
      }
    },
    "/users/{user_id}/albums/{album_id}/logos/{logo_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album logos"
        ],
        "description": "This method removes a custom logo from the specified album.",
        "operationId": "delete_album_logo",
        "summary": "Remove a custom album logo"
      },
      "get": {
        "tags": [
          "Albums\\Custom album logos"
        ],
        "operationId": "get_album_logo",
        "summary": "Get a specific custom album logo"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Custom album logos"
        ],
        "operationId": "replace_album_logo",
        "summary": "Replace a custom album logo"
      }
    },
    "/users/{user_id}/albums/{album_id}/videos": {
      "get": {
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "get_album_videos",
        "summary": "Get all the videos in an album"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "description": "This method replaces all the existing videos in an album with one or more videos.",
        "operationId": "replace_videos_in_album",
        "summary": "Replace all the videos in an album"
      }
    },
    "/users/{user_id}/albums/{album_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "remove_video_from_album",
        "summary": "Remove a video from an album"
      },
      "get": {
        "tags": [
          "Albums\\Album videos"
        ],
        "description": "This method gets a single video from an album. You can use this method to determine whether the album contains the specified video.",
        "operationId": "get_album_video",
        "summary": "Get a specific video in an album"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "add_video_to_album",
        "summary": "Add a specific video to an album"
      }
    },
    "/users/{user_id}/albums/{album_id}/videos/{video_id}/set_album_thumbnail": {
      "post": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Albums\\Album videos"
        ],
        "operationId": "set_video_as_album_thumbnail",
        "summary": "Set a video as the album thumbnail"
      }
    },
    "/users/{user_id}/appearances": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "get_appearances",
        "summary": "Get all the videos in which a user appears"
      }
    },
    "/users/{user_id}/categories": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "get_category_subscriptions",
        "summary": "Get all the categories that a user follows"
      }
    },
    "/users/{user_id}/categories/{category}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "unsubscribe_from_category",
        "summary": "Unsubscribe a user from a category"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "check_if_user_subscribed_to_category",
        "summary": "Check if a user follows a category"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Categories\\Subscriptions"
        ],
        "operationId": "subscribe_to_category",
        "summary": "Subscribe a user to a single category"
      }
    },
    "/users/{user_id}/channels": {
      "get": {
        "tags": [
          "Channels\\Essentials"
        ],
        "operationId": "get_channel_subscriptions",
        "summary": "Get all the channels to which a user subscribes"
      }
    },
    "/users/{user_id}/channels/{channel_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "unsubscribe_from_channel",
        "summary": "Unsubscribe a user from a specific channel"
      },
      "get": {
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "check_if_user_subscribed_to_channel",
        "summary": "Check if a user follows a channel"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Channels\\Subscriptions and subscribers"
        ],
        "operationId": "subscribe_to_channel",
        "summary": "Subscribe a user to a specific channel"
      }
    },
    "/users/{user_id}/customlogos": {
      "get": {
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "get_custom_logos",
        "summary": "Get all the custom logos that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "create_custom_logo",
        "summary": "Add a custom logo"
      }
    },
    "/users/{user_id}/customlogos/{logo_id}": {
      "get": {
        "tags": [
          "Embed Presets\\Custom Logos"
        ],
        "operationId": "get_custom_logo",
        "summary": "Get a specific custom logo"
      }
    },
    "/users/{user_id}/feed": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Users\\Feed"
        ],
        "operationId": "get_feed",
        "summary": "Get all videos in a user's feed"
      }
    },
    "/users/{user_id}/followers": {
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "get_followers",
        "summary": "Get all the followers of a user"
      }
    },
    "/users/{user_id}/following": {
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "get_user_following",
        "summary": "Get all the users that a user is following"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "follow_users",
        "summary": "Follow a list of users"
      }
    },
    "/users/{user_id}/following/{follow_user_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "unfollow_user",
        "summary": "Unfollow a user"
      },
      "get": {
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "check_if_user_is_following",
        "summary": "Check if a user is following another user"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Users\\Follows"
        ],
        "operationId": "follow_user",
        "summary": "Follow a specific user"
      }
    },
    "/users/{user_id}/groups": {
      "get": {
        "tags": [
          "Groups\\Users"
        ],
        "operationId": "get_user_groups",
        "summary": "Get all the groups that a user has joined"
      }
    },
    "/users/{user_id}/groups/{group_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Groups\\Subscription"
        ],
        "operationId": "leave_group",
        "summary": "Remove a user from a group"
      },
      "get": {
        "tags": [
          "Groups\\Users"
        ],
        "operationId": "check_if_user_joined_group",
        "summary": "Check if a user has joined a group"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Groups\\Subscription"
        ],
        "operationId": "join_group",
        "summary": "Add a user to a group"
      }
    },
    "/users/{user_id}/likes": {
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "get_likes",
        "summary": "Get all the videos that a user has liked"
      }
    },
    "/users/{user_id}/likes/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "unlike_video",
        "summary": "Cause a user to unlike a video"
      },
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "check_if_user_liked_video",
        "summary": "Check if a user has liked a video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "like_video",
        "summary": "Cause a user to like a video"
      }
    },
    "/users/{user_id}/ondemand/pages": {
      "get": {
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "get_user_vods",
        "summary": "Get all the On Demand pages of a user"
      },
      "post": {
        "tags": [
          "On Demand\\Essentials"
        ],
        "operationId": "create_vod",
        "summary": "Create an On Demand page"
      }
    },
    "/users/{user_id}/ondemand/purchases": {
      "get": {
        "security": [
          {
            "oauth2": [
              "purchased"
            ]
          }
        ],
        "tags": [
          "On Demand\\Purchases and Rentals"
        ],
        "operationId": "check_if_vod_was_purchased",
        "summary": "Check if a user has made a purchase or rental from an On Demand page"
      }
    },
    "/users/{user_id}/pictures": {
      "get": {
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "get_pictures",
        "summary": "Get all the pictures that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "create_picture",
        "summary": "Add a user picture"
      }
    },
    "/users/{user_id}/pictures/{portraitset_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "delete_picture",
        "summary": "Delete a user picture"
      },
      "get": {
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "get_picture",
        "summary": "Get a specific user picture"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Users\\Pictures"
        ],
        "operationId": "edit_picture",
        "summary": "Edit a user picture"
      }
    },
    "/users/{user_id}/portfolios": {
      "get": {
        "tags": [
          "Portfolios\\Essentials"
        ],
        "operationId": "get_portfolios",
        "summary": "Get all the portfolios that belong to a user"
      }
    },
    "/users/{user_id}/portfolios/{portfolio_id}": {
      "get": {
        "tags": [
          "Portfolios\\Essentials"
        ],
        "operationId": "get_portfolio",
        "summary": "Get a specific portfolio"
      }
    },
    "/users/{user_id}/portfolios/{portfolio_id}/videos": {
      "get": {
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "get_portfolio_videos",
        "summary": "Get all the videos in a portfolio"
      }
    },
    "/users/{user_id}/portfolios/{portfolio_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "delete_video_from_portfolio",
        "summary": "Remove a video from a portfolio"
      },
      "get": {
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "get_portfolio_video",
        "summary": "Get a specific video in a portfolio"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Portfolios\\Videos"
        ],
        "operationId": "add_video_to_portfolio",
        "summary": "Add a video to a portfolio"
      }
    },
    "/users/{user_id}/presets": {
      "get": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "get_embed_presets",
        "summary": "Get all the embed presets that a user has created"
      }
    },
    "/users/{user_id}/presets/{preset_id}": {
      "get": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "get_embed_preset",
        "summary": "Get a specific embed preset"
      },
      "patch": {
        "tags": [
          "Embed Presets\\Essentials"
        ],
        "operationId": "edit_embed_preset",
        "summary": "Edit an embed preset"
      }
    },
    "/users/{user_id}/presets/{preset_id}/videos": {
      "get": {
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "get_embed_preset_videos",
        "summary": "Get all the videos that have been added to an embed preset"
      }
    },
    "/users/{user_id}/projects": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method gets all the projects that belong to the specified user.",
        "operationId": "get_projects",
        "summary": "Get all the projects that belong to a user"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "create"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method creates a new project for the specified user.",
        "operationId": "create_project",
        "summary": "Create a project"
      }
    },
    "/users/{user_id}/projects/{project_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method deletes a project and optionally also the videos that it contains.",
        "operationId": "delete_project",
        "summary": "Delete a project"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method gets a single project that belongs to the specified user.",
        "operationId": "get_project",
        "summary": "Get a specific project"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Projects\\Essentials"
        ],
        "description": "This method edits an existing project.",
        "operationId": "edit_project",
        "summary": "Edit a project"
      }
    },
    "/users/{user_id}/projects/{project_id}/videos": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method removed multiple videos from the specified project.",
        "operationId": "remove_videos_from_project",
        "summary": "Remove a list of videos from a project"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method gets all the videos that belong to the specified project.",
        "operationId": "get_project_videos",
        "summary": "Get all the videos in a project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method adds multiple videos to the specified project.",
        "operationId": "add_videos_to_project",
        "summary": "Add a list of videos to a project"
      }
    },
    "/users/{user_id}/projects/{project_id}/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method removes a single video from the specified project.",
        "operationId": "remove_video_from_project",
        "summary": "Remove a specific video from a project"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Projects\\Videos"
        ],
        "description": "This method adds a single video to the specified project.",
        "operationId": "add_video_to_project",
        "summary": "Add a specific video to a project"
      }
    },
    "/users/{user_id}/uploads/{upload}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Upload"
        ],
        "operationId": "complete_streaming_upload",
        "summary": "Complete a user's streaming upload"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Upload"
        ],
        "operationId": "get_upload_attempt",
        "summary": "Get a user's upload attempt"
      }
    },
    "/users/{user_id}/videos": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "get_videos",
        "summary": "Get all the videos that a user has uploaded"
      },
      "post": {
        "tags": [
          "Videos\\Upload"
        ],
        "description": "Begin the video upload process. For more information, see our [upload documentation](https://developer.vimeo.com/api/upload/videos).",
        "operationId": "upload_video",
        "summary": "Upload a video"
      }
    },
    "/users/{user_id}/videos/{video_id}": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "check_if_user_owns_video",
        "summary": "Check if a user owns a video"
      }
    },
    "/users/{user_id}/watchlater": {
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "get_watch_later_queue",
        "summary": "Get all the videos in a user's Watch Later queue"
      }
    },
    "/users/{user_id}/watchlater/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "delete_video_from_watch_later",
        "summary": "Remove a video from a user's Watch Later queue"
      },
      "get": {
        "security": [
          {
            "oauth2": [
              "private"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "check_watch_later_queue",
        "summary": "Check if a user has added a specific video to their Watch Later queue"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Watch Later Queue\\Essentials"
        ],
        "operationId": "add_video_to_watch_later",
        "summary": "Add a video to a user's Watch Later queue"
      }
    },
    "/videos": {
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "search_videos",
        "summary": "Search for videos"
      }
    },
    "/videos/{video_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "delete_video",
        "summary": "Delete a video"
      },
      "get": {
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "get_video",
        "summary": "Get a specific video"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Essentials"
        ],
        "operationId": "edit_video",
        "summary": "Edit a video"
      }
    },
    "/videos/{video_id}/available_channels": {
      "get": {
        "tags": [
          "Channels\\Videos"
        ],
        "operationId": "get_available_video_channels",
        "summary": "Get all the channels to which a user can add or remove a specific video"
      }
    },
    "/videos/{video_id}/categories": {
      "get": {
        "tags": [
          "Categories\\Videos"
        ],
        "operationId": "get_video_categories",
        "summary": "Get all the categories to which a video belongs"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Categories\\Videos"
        ],
        "description": "With this method, you can suggest up to two categories and one subcategory for a video. Vimeo makes the final determination about whether the video\nbelongs in these categories.",
        "operationId": "suggest_video_category",
        "summary": "Suggest categories for a video"
      }
    },
    "/videos/{video_id}/comments": {
      "get": {
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "get_comments",
        "summary": "Get all the comments on a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "create_comment",
        "summary": "Add a comment to a video"
      }
    },
    "/videos/{video_id}/comments/{comment_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "delete_comment",
        "summary": "Delete a video comment"
      },
      "get": {
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "get_comment",
        "summary": "Get a specific video comment"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "edit_comment",
        "summary": "Edit a video comment"
      }
    },
    "/videos/{video_id}/comments/{comment_id}/replies": {
      "get": {
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "get_comment_replies",
        "summary": "Get all the replies to a video comment"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "interact"
            ]
          }
        ],
        "tags": [
          "Videos\\Comments"
        ],
        "operationId": "create_comment_reply",
        "summary": "Add a reply to a video comment"
      }
    },
    "/videos/{video_id}/credits": {
      "get": {
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "get_video_credits",
        "summary": "Get all the credited users in a video"
      },
      "post": {
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "add_video_credit",
        "summary": "Credit a user in a video"
      }
    },
    "/videos/{video_id}/credits/{credit_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "delete_video_credit",
        "summary": "Delete a credit for a user in a video"
      },
      "get": {
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "get_video_credit",
        "summary": "Get a specific credited user in a video"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Credits"
        ],
        "operationId": "edit_video_credit",
        "summary": "Edit a credit for a user in a video"
      }
    },
    "/videos/{video_id}/likes": {
      "get": {
        "tags": [
          "Likes\\Essentials"
        ],
        "operationId": "get_video_likes",
        "summary": "Get all the users who have liked a video"
      }
    },
    "/videos/{video_id}/pictures": {
      "get": {
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "get_video_thumbnails",
        "summary": "Get all the thumbnails of a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "create_video_thumbnail",
        "summary": "Add a video thumbnail"
      }
    },
    "/videos/{video_id}/pictures/{picture_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "delete_video_thumbnail",
        "summary": "Delete a video thumbnail"
      },
      "get": {
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "get_video_thumbnail",
        "summary": "Get a video thumbnail"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Thumbnails"
        ],
        "operationId": "edit_video_thumbnail",
        "summary": "Edit a video thumbnail"
      }
    },
    "/videos/{video_id}/presets/{preset_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "delete_video_embed_preset",
        "summary": "Remove an embed preset from a video"
      },
      "get": {
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "get_video_embed_preset",
        "summary": "Check if an embed preset has been added to a video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "add_video_embed_preset",
        "summary": "Add an embed preset to a video"
      }
    },
    "/videos/{video_id}/privacy/domains": {
      "get": {
        "tags": [
          "Videos\\Embed Privacy"
        ],
        "operationId": "get_video_privacy_domains",
        "summary": "Get all the domains on which a video can be embedded"
      }
    },
    "/videos/{video_id}/privacy/domains/{domain}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Embed Privacy"
        ],
        "operationId": "delete_video_privacy_domain",
        "summary": "Restrict a video from being embedded on a domain"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Embed Privacy"
        ],
        "description": "If domain privacy is enabled for this video, this method permits the video to be embedded on the specified domain.",
        "operationId": "add_video_privacy_domain",
        "summary": "Permit a video to be embedded on a domain"
      }
    },
    "/videos/{video_id}/privacy/users": {
      "get": {
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "operationId": "get_video_privacy_users",
        "summary": "Get all the users who can view a user's private videos by default"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "description": "The body of this request should follow our\n[batch request format](https://developer.vimeo.com/api/common-formats#batch-requests). Each object must contain\na single `URI` field, and the value of this field must be the URI of the user who can view this video.",
        "operationId": "add_video_privacy_users",
        "summary": "Permit a list of users to view a private video"
      }
    },
    "/videos/{video_id}/privacy/users/{user_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "operationId": "delete_video_privacy_user",
        "summary": "Restrict a user from viewing a private video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Viewing Privacy"
        ],
        "operationId": "add_video_privacy_user",
        "summary": "Permit a specific user to view a private video"
      }
    },
    "/videos/{video_id}/tags": {
      "get": {
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "get_video_tags",
        "summary": "Get all the tags of a video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "add_video_tags",
        "summary": "Add a list of tags to a video"
      }
    },
    "/videos/{video_id}/tags/{word}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "delete_video_tag",
        "summary": "Remove a tag from a video"
      },
      "get": {
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "check_video_for_tag",
        "summary": "Check if a tag has been added to a video"
      },
      "put": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Tags"
        ],
        "operationId": "add_video_tag",
        "summary": "Add a specific tag to a video"
      }
    },
    "/videos/{video_id}/texttracks": {
      "get": {
        "tags": [
          "Videos\\Text Tracks"
        ],
        "operationId": "get_text_tracks",
        "summary": "Get all the text tracks of a video"
      },
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Videos\\Text Tracks"
        ],
        "description": "For additional information, see our [text track upload guide](https://developer.vimeo.com/api/upload/texttracks).",
        "operationId": "create_text_track",
        "summary": "Add a text track to a video"
      }
    },
    "/videos/{video_id}/texttracks/{texttrack_id}": {
      "delete": {
        "security": [
          {
            "oauth2": [
              "delete"
            ]
          }
        ],
        "tags": [
          "Videos\\Text Tracks"
        ],
        "operationId": "delete_text_track",
        "summary": "Delete a text track"
      },
      "get": {
        "tags": [
          "Videos\\Text Tracks"
        ],
        "operationId": "get_text_track",
        "summary": "Get a specific text track"
      },
      "patch": {
        "security": [
          {
            "oauth2": [
              "edit"
            ]
          }
        ],
        "tags": [
          "Videos\\Text Tracks"
        ],
        "operationId": "edit_text_track",
        "summary": "Edit a text track"
      }
    },
    "/videos/{video_id}/timelinethumbnails": {
      "post": {
        "security": [
          {
            "oauth2": [
              "upload"
            ]
          }
        ],
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "create_video_custom_logo",
        "summary": "Add a new custom logo to a video"
      }
    },
    "/videos/{video_id}/timelinethumbnails/{thumbnail_id}": {
      "get": {
        "tags": [
          "Embed Presets\\Videos"
        ],
        "operationId": "get_video_custom_logo",
        "summary": "Get a custom video logo"
      }
    },
    "/videos/{video_id}/versions": {
      "post": {
        "tags": [
          "Videos\\Versions"
        ],
        "operationId": "create_video_version",
        "summary": "Add a version to a video"
      }
    },
    "/videos/{video_id}/videos": {
      "get": {
        "tags": [
          "Videos\\Recommendations"
        ],
        "operationId": "get_related_videos",
        "summary": "Get all the related videos of a video"
      }
    }
  },
  "securityDefinitions": {
    "bearer": {
      "in": "header",
      "name": "Authorization",
      "type": "apiKey"
    },
    "oauth2": {
      "authorizationUrl": "/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "create": "Create new albums, channels, and so on",
        "delete": "Delete videos, albums, channels, and so on",
        "edit": "Edit existing videos, albums, channels, and so on",
        "email": "Access to email addresses",
        "interact": "Interact with Vimeo resources on a member's behalf, such as liking a video or following another member",
        "private": "Access private member data",
        "promo_codes": "Add, remove, and review Vimeo On Demand promotions",
        "public": "Access public member data",
        "purchase": "Purchase content",
        "purchased": "Access a member's Vimeo On Demand purchase history",
        "stats": "Access video stats",
        "upload": "Upload videos",
        "video_files": "Access video files belonging to members with a PRO subscription or higher"
      },
      "tokenUrl": "/oauth/access_token",
      "type": "oauth2"
    }
  },
  "security": [
    {
      "oauth2": [
        "create",
        "delete",
        "edit",
        "email",
        "interact",
        "private",
        "promo_codes",
        "public",
        "purchase",
        "purchased",
        "stats",
        "upload",
        "video_files"
      ]
    }
  ],
  "tags": [
    {
      "name": "API Information"
    },
    {
      "name": "Albums\\Album videos"
    },
    {
      "name": "Albums\\Custom album logos"
    },
    {
      "name": "Albums\\Custom album thumbnails"
    },
    {
      "name": "Albums\\Essentials"
    },
    {
      "name": "Authentication Extras\\Essentials"
    },
    {
      "name": "Categories\\Channels"
    },
    {
      "name": "Categories\\Essentials"
    },
    {
      "name": "Categories\\Groups"
    },
    {
      "name": "Categories\\Subscriptions"
    },
    {
      "name": "Categories\\Videos"
    },
    {
      "name": "Channels\\Categories"
    },
    {
      "name": "Channels\\Essentials"
    },
    {
      "name": "Channels\\Moderators"
    },
    {
      "name": "Channels\\Private channel members"
    },
    {
      "name": "Channels\\Subscriptions and subscribers"
    },
    {
      "name": "Channels\\Tags"
    },
    {
      "name": "Channels\\Videos"
    },
    {
      "name": "Embed Presets\\Custom Logos"
    },
    {
      "name": "Embed Presets\\Essentials"
    },
    {
      "name": "Embed Presets\\Videos"
    },
    {
      "name": "Groups\\Essentials"
    },
    {
      "name": "Groups\\Subscription"
    },
    {
      "name": "Groups\\Users"
    },
    {
      "name": "Groups\\Videos"
    },
    {
      "name": "Likes\\Essentials"
    },
    {
      "name": "On Demand\\Backgrounds"
    },
    {
      "name": "On Demand\\Essentials"
    },
    {
      "name": "On Demand\\Genres"
    },
    {
      "name": "On Demand\\Posters"
    },
    {
      "name": "On Demand\\Promotions"
    },
    {
      "name": "On Demand\\Purchases and Rentals"
    },
    {
      "name": "On Demand\\Regions"
    },
    {
      "name": "On Demand\\Seasons"
    },
    {
      "name": "On Demand\\Videos"
    },
    {
      "name": "Portfolios\\Essentials"
    },
    {
      "name": "Portfolios\\Videos"
    },
    {
      "name": "Projects\\Essentials"
    },
    {
      "name": "Projects\\Videos"
    },
    {
      "name": "Tags\\Essentials"
    },
    {
      "name": "Users\\Essentials"
    },
    {
      "name": "Users\\Feed"
    },
    {
      "name": "Users\\Follows"
    },
    {
      "name": "Users\\Internal"
    },
    {
      "name": "Users\\Pictures"
    },
    {
      "name": "Users\\Watch History"
    },
    {
      "name": "Videos\\Comments"
    },
    {
      "name": "Videos\\Content Ratings"
    },
    {
      "name": "Videos\\Creative Commons"
    },
    {
      "name": "Videos\\Credits"
    },
    {
      "name": "Videos\\Embed Privacy"
    },
    {
      "name": "Videos\\Essentials"
    },
    {
      "name": "Videos\\Languages"
    },
    {
      "name": "Videos\\Recommendations"
    },
    {
      "name": "Videos\\Tags"
    },
    {
      "name": "Videos\\Text Tracks"
    },
    {
      "name": "Videos\\Thumbnails"
    },
    {
      "name": "Videos\\Upload"
    },
    {
      "name": "Videos\\Versions"
    },
    {
      "name": "Videos\\Viewing Privacy"
    },
    {
      "name": "Watch Later Queue\\Essentials"
    }
  ],
  "x-components": {}
}