{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "script.googleapis.com",
  "basePath": "/",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "An API for managing and executing Google Apps Script projects.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Apps Script",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "cloud"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.gstatic.com_images_icons_material_product_2x_apps_script_64dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.6.0"
        },
        "format": "google",
        "url": "https://script.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "script",
    "x-datafire": {
      "name": "google_script",
      "type": "openapi"
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://mail.google.com/": "Read, send, delete, and manage your email",
        "https://www.google.com/calendar/feeds": "Manage your calendars",
        "https://www.google.com/m8/feeds": "Manage your contacts",
        "https://www.googleapis.com/auth/admin.directory.group": "View and manage the provisioning of groups on your domain",
        "https://www.googleapis.com/auth/admin.directory.user": "View and manage the provisioning of users on your domain",
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/forms": "View and manage your forms in Google Drive",
        "https://www.googleapis.com/auth/forms.currentonly": "View and manage forms that this application has been installed in",
        "https://www.googleapis.com/auth/groups": "View and manage your Google Groups",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 accessCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://mail.google.com/": "Read, send, delete, and manage your email",
        "https://www.google.com/calendar/feeds": "Manage your calendars",
        "https://www.google.com/m8/feeds": "Manage your contacts",
        "https://www.googleapis.com/auth/admin.directory.group": "View and manage the provisioning of groups on your domain",
        "https://www.googleapis.com/auth/admin.directory.user": "View and manage the provisioning of users on your domain",
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/forms": "View and manage your forms in Google Drive",
        "https://www.googleapis.com/auth/forms.currentonly": "View and manage forms that this application has been installed in",
        "https://www.googleapis.com/auth/groups": "View and manage your Google Groups",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    },
    "offline": {
      "type": "oauth2",
      "flow": "accessCode",
      "scopes": {
        "https://mail.google.com/": "Read, send, delete, and manage your email",
        "https://www.google.com/calendar/feeds": "Manage your calendars",
        "https://www.google.com/m8/feeds": "Manage your contacts",
        "https://www.googleapis.com/auth/admin.directory.group": "View and manage the provisioning of groups on your domain",
        "https://www.googleapis.com/auth/admin.directory.user": "View and manage the provisioning of users on your domain",
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/forms": "View and manage your forms in Google Drive",
        "https://www.googleapis.com/auth/forms.currentonly": "View and manage forms that this application has been installed in",
        "https://www.googleapis.com/auth/groups": "View and manage your Google Groups",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address"
      },
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "description": "Allows offline access using a refresh_token"
    }
  },
  "tags": [
    {
      "name": "processes"
    },
    {
      "name": "projects"
    },
    {
      "name": "scripts"
    }
  ],
  "paths": {
    "/v1/processes": {
      "get": {
        "description": "List information about processes made by or on behalf of a user,\nsuch as process type and current status.",
        "operationId": "processes.list",
        "tags": [
          "processes"
        ]
      }
    },
    "/v1/processes:listScriptProcesses": {
      "get": {
        "description": "List information about a script's executed processes, such as process type\nand current status.",
        "operationId": "processes.listScriptProcesses",
        "tags": [
          "processes"
        ]
      }
    },
    "/v1/projects": {
      "post": {
        "description": "Creates a new, empty script project with no script files and a base\nmanifest file.",
        "operationId": "projects.create",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}": {
      "get": {
        "description": "Gets a script project's metadata.",
        "operationId": "projects.get",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/content": {
      "get": {
        "description": "Gets the content of the script project, including the code source and\nmetadata for each script file.",
        "operationId": "projects.getContent",
        "tags": [
          "projects"
        ]
      },
      "put": {
        "description": "Updates the content of the specified script project.\nThis content is stored as the HEAD version, and is used when the script is\nexecuted as a trigger, in the script editor, in add-on preview mode, or as\na web app or Apps Script API in development mode. This clears all the\nexisting files in the project.",
        "operationId": "projects.updateContent",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/deployments": {
      "get": {
        "description": "Lists the deployments of an Apps Script project.",
        "operationId": "projects.deployments.list",
        "tags": [
          "projects"
        ]
      },
      "post": {
        "description": "Creates a deployment of an Apps Script project.",
        "operationId": "projects.deployments.create",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/deployments/{deploymentId}": {
      "delete": {
        "description": "Deletes a deployment of an Apps Script project.",
        "operationId": "projects.deployments.delete",
        "tags": [
          "projects"
        ]
      },
      "get": {
        "description": "Gets a deployment of an Apps Script project.",
        "operationId": "projects.deployments.get",
        "tags": [
          "projects"
        ]
      },
      "put": {
        "description": "Updates a deployment of an Apps Script project.",
        "operationId": "projects.deployments.update",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/metrics": {
      "get": {
        "description": "Get metrics data for scripts, such as number of executions and\nactive users.",
        "operationId": "projects.getMetrics",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/versions": {
      "get": {
        "description": "List the versions of a script project.",
        "operationId": "projects.versions.list",
        "tags": [
          "projects"
        ]
      },
      "post": {
        "description": "Creates a new immutable version using the current code, with a unique\nversion number.",
        "operationId": "projects.versions.create",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/projects/{scriptId}/versions/{versionNumber}": {
      "get": {
        "description": "Gets a version of a script project.",
        "operationId": "projects.versions.get",
        "tags": [
          "projects"
        ]
      }
    },
    "/v1/scripts/{scriptId}:run": {
      "post": {
        "description": "Runs a function in an Apps Script project. The project must be deployed\nfor use with the Apps Script API.\n\nThis method requires authorization with an OAuth 2.0 token that includes at\nleast one of the scopes listed in the [Authorization](#authorization)\nsection; script projects that do not require authorization cannot be\nexecuted through this API. To find the correct scopes to include in the\nauthentication token, open the project in the script editor, then select\n*[...]",
        "operationId": "scripts.run",
        "security": [
          {
            "Oauth2": [
              "https://mail.google.com/"
            ],
            "Oauth2c": [
              "https://mail.google.com/"
            ]
          },
          {
            "Oauth2": [
              "https://www.google.com/calendar/feeds"
            ],
            "Oauth2c": [
              "https://www.google.com/calendar/feeds"
            ]
          },
          {
            "Oauth2": [
              "https://www.google.com/m8/feeds"
            ],
            "Oauth2c": [
              "https://www.google.com/m8/feeds"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.directory.group"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.directory.group"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/admin.directory.user"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/admin.directory.user"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/forms"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/forms"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/forms.currentonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/forms.currentonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/groups"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/groups"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/spreadsheets"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/spreadsheets"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          }
        ],
        "tags": [
          "scripts"
        ]
      }
    }
  }
}