{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "Archiving and eDiscovery for G Suite.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "G Suite Vault API",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.7.31"
        },
        "format": "google",
        "url": "https://vault.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "vault",
    "x-datafire": {
      "name": "google_vault",
      "type": "openapi"
    }
  },
  "host": "vault.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/matters": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Lists matters the user has access to.",
        "operationId": "vault.matters.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Creates a new matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
        "operationId": "vault.matters.create"
      }
    },
    "/v1/matters/{matterId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Deletes the specified matter. Returns matter with updated state.",
        "operationId": "vault.matters.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Gets the specified matter.",
        "operationId": "vault.matters.get"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
        "operationId": "vault.matters.update"
      }
    },
    "/v1/matters/{matterId}/exports": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Lists Exports.",
        "operationId": "vault.matters.exports.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Creates an Export.",
        "operationId": "vault.matters.exports.create"
      }
    },
    "/v1/matters/{matterId}/exports/{exportId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Deletes an Export.",
        "operationId": "vault.matters.exports.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Gets an Export.",
        "operationId": "vault.matters.exports.get"
      }
    },
    "/v1/matters/{matterId}/holds": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Lists holds within a matter. An empty page token in ListHoldsResponse denotes no more holds to list.",
        "operationId": "vault.matters.holds.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Creates a hold in the given matter.",
        "operationId": "vault.matters.holds.create"
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Removes a hold by ID. This will release any HeldAccounts on this Hold.",
        "operationId": "vault.matters.holds.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Gets a hold by ID.",
        "operationId": "vault.matters.holds.get"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Updates the OU and/or query parameters of a hold. You cannot add accounts to a hold that covers an OU, nor can you add OUs to a hold that covers individual accounts. Accounts listed in the hold will be ignored.",
        "operationId": "vault.matters.holds.update"
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}/accounts": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Lists HeldAccounts for a hold. This will only list individually specified held accounts. If the hold is on an OU, then use Admin SDK to enumerate its members.",
        "operationId": "vault.matters.holds.accounts.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Adds a HeldAccount to a hold. Accounts can only be added to a hold that has no held_org_unit set. Attempting to add an account to an OU-based hold will result in an error.",
        "operationId": "vault.matters.holds.accounts.create"
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Removes a HeldAccount from a hold. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
        "operationId": "vault.matters.holds.accounts.delete"
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}:addHeldAccounts": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Adds HeldAccounts to a hold. Returns a list of accounts that have been successfully added. Accounts can only be added to an existing account-based hold.",
        "operationId": "vault.matters.holds.addHeldAccounts"
      }
    },
    "/v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Removes HeldAccounts from a hold. Returns a list of statuses in the same order as the request. If this request leaves the hold with no held accounts, the hold will not apply to any accounts.",
        "operationId": "vault.matters.holds.removeHeldAccounts"
      }
    },
    "/v1/matters/{matterId}/savedQueries": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Lists saved queries within a matter. An empty page token in ListSavedQueriesResponse denotes no more saved queries to list.",
        "operationId": "vault.matters.savedQueries.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Creates a saved query.",
        "operationId": "vault.matters.savedQueries.create"
      }
    },
    "/v1/matters/{matterId}/savedQueries/{savedQueryId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Deletes a saved query by Id.",
        "operationId": "vault.matters.savedQueries.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery.readonly"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Retrieves a saved query by Id.",
        "operationId": "vault.matters.savedQueries.get"
      }
    },
    "/v1/matters/{matterId}:addPermissions": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Adds an account as a matter collaborator.",
        "operationId": "vault.matters.addPermissions"
      }
    },
    "/v1/matters/{matterId}:close": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Closes the specified matter. Returns matter with updated state.",
        "operationId": "vault.matters.close"
      }
    },
    "/v1/matters/{matterId}:count": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Counts the artifacts within the context of a matter and returns a detailed breakdown of metrics.",
        "operationId": "vault.matters.count"
      }
    },
    "/v1/matters/{matterId}:removePermissions": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Removes an account as a matter collaborator.",
        "operationId": "vault.matters.removePermissions"
      }
    },
    "/v1/matters/{matterId}:reopen": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Reopens the specified matter. Returns matter with updated state.",
        "operationId": "vault.matters.reopen"
      }
    },
    "/v1/matters/{matterId}:undelete": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/ediscovery"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/ediscovery"
            ]
          }
        ],
        "tags": [
          "matters"
        ],
        "description": "Undeletes the specified matter. Returns matter with updated state.",
        "operationId": "vault.matters.undelete"
      }
    },
    "/v1/{name}": {
      "delete": {
        "tags": [
          "operations"
        ],
        "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
        "operationId": "vault.operations.delete"
      },
      "get": {
        "tags": [
          "operations"
        ],
        "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. NOTE: the `name` binding allows API services to override the binding to use different resource name schemes, such as `users/*/operations`. To override the binding, API services can add a binding such as `\"/v1/{name=users/*}/operations\"` to their service configuration. For backwards compatibility, the default name includes the operations[...]",
        "operationId": "vault.operations.list"
      }
    },
    "/v1/{name}:cancel": {
      "post": {
        "tags": [
          "operations"
        ],
        "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an o[...]",
        "operationId": "vault.operations.cancel"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": "Manage your eDiscovery data",
        "https://www.googleapis.com/auth/ediscovery.readonly": "View your eDiscovery data"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": "Manage your eDiscovery data",
        "https://www.googleapis.com/auth/ediscovery.readonly": "View your eDiscovery data"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "matters"
    },
    {
      "name": "operations"
    }
  ],
  "x-components": {
  }
}