const list = [
  "acm",
  "apigateway",
  "appstream2",
  "athena",
  "autoscaling",
  "batch",
  "budgets",
  "clouddirectory",
  "cloudformation",
  "cloudfront",
  "cloudhsm",
  "cloudsearch",
  "cloudsearchdomain",
  "cloudtrail",
  "codebuild",
  "codecommit",
  "codedeploy",
  "codepipeline",
  "codestar",
  "cognito_identity",
  "cognito_idp",
  "cognito_sync",
  "config",
  "cur",
  "data_iot",
  "datapipeline",
  "dax",
  "devicefarm",
  "directconnect",
  "discovery",
  "dms",
  "ds",
  "dynamodb",
  "ec2",
  "ecr",
  "ecs",
  "elasticache",
  "elasticbeanstalk",
  "elasticfilesystem",
  "elasticloadbalancing",
  "elasticmapreduce",
  "elastictranscoder",
  "email",
  "entitlement_marketplace",
  "es",
  "events",
  "firehose",
  "gamelift",
  "glacier",
  "greengrass",
  "health",
  "iam",
  "importexport",
  "inspector",
  "iot",
  "kinesis",
  "kinesisanalytics",
  "kms",
  "lambda",
  "lightsail",
  "machinelearning",
  "marketplacecommerceanalytics",
  "metering_marketplace",
  "mobileanalytics",
  "models_lex",
  "monitoring",
  "mturk_requester",
  "opsworks",
  "opsworks_cm",
  "organizations",
  "pinpoint",
  "polly",
  "rds",
  "redshift",
  "rekognition",
  "route53",
  "route53domains",
  "runtime_lex",
  "s3",
  "sdb",
  "servicecatalog",
  "shield",
  "sms",
  "snowball",
  "sns",
  "sqs",
  "ssm",
  "states",
  "storagegateway",
  "streams_dynamodb",
  "sts",
  "support",
  "swf",
  "tagging",
  "waf",
  "waf_regional",
  "workdocs",
  "workspaces",
  "xray",
];

const sdkMap = module.exports = {
  'appstream2': 'AppStream',
}

let sdk = require('aws-sdk');
list.forEach(name => {
  let objName = sdkMap[name] || Object.keys(sdk).filter(serviceName => {
    return serviceName.toLowerCase() === name.replace(/_/g, '');
  });
  if (!objName) throw new Error("obj name not found for " + name);
  sdkMap[name] = objName;
})
