{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Interacts with Glass users via the timeline.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Mirror",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.7.31"
        },
        "format": "google",
        "url": "https://www.googleapis.com/discovery/v1/apis/mirror/v1/rest",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "mirror",
    "x-datafire": {
      "name": "google_mirror",
      "type": "openapi"
    }
  },
  "host": "www.googleapis.com",
  "basePath": "/mirror/v1",
  "schemes": [
    "https"
  ],
  "paths": {
    "/accounts/{userToken}/{accountType}/{accountName}": {
      "post": {
        "tags": [
          "accounts"
        ],
        "description": "Inserts a new account for a user",
        "operationId": "mirror.accounts.insert"
      }
    },
    "/contacts": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Retrieves a list of contacts for the authenticated user.",
        "operationId": "mirror.contacts.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Inserts a new contact.",
        "operationId": "mirror.contacts.insert"
      }
    },
    "/contacts/{id}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Deletes a contact.",
        "operationId": "mirror.contacts.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Gets a single contact by ID.",
        "operationId": "mirror.contacts.get"
      },
      "patch": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Updates a contact in place. This method supports patch semantics.",
        "operationId": "mirror.contacts.patch"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "contacts"
        ],
        "description": "Updates a contact in place.",
        "operationId": "mirror.contacts.update"
      }
    },
    "/locations": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "locations"
        ],
        "description": "Retrieves a list of locations for the user.",
        "operationId": "mirror.locations.list"
      }
    },
    "/locations/{id}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "locations"
        ],
        "description": "Gets a single location by ID.",
        "operationId": "mirror.locations.get"
      }
    },
    "/settings/{id}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "settings"
        ],
        "description": "Gets a single setting by ID.",
        "operationId": "mirror.settings.get"
      }
    },
    "/subscriptions": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ],
        "description": "Retrieves a list of subscriptions for the authenticated user and service.",
        "operationId": "mirror.subscriptions.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ],
        "description": "Creates a new subscription.",
        "operationId": "mirror.subscriptions.insert"
      }
    },
    "/subscriptions/{id}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ],
        "description": "Deletes a subscription.",
        "operationId": "mirror.subscriptions.delete"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "subscriptions"
        ],
        "description": "Updates an existing subscription in place.",
        "operationId": "mirror.subscriptions.update"
      }
    },
    "/timeline": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Retrieves a list of timeline items for the authenticated user.",
        "operationId": "mirror.timeline.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Inserts a new item into the timeline.",
        "operationId": "mirror.timeline.insert"
      }
    },
    "/timeline/{id}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Deletes a timeline item.",
        "operationId": "mirror.timeline.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Gets a single timeline item by ID.",
        "operationId": "mirror.timeline.get"
      },
      "patch": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Updates a timeline item in place. This method supports patch semantics.",
        "operationId": "mirror.timeline.patch"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.location"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.location"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Updates a timeline item in place.",
        "operationId": "mirror.timeline.update"
      }
    },
    "/timeline/{itemId}/attachments": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Returns a list of attachments for a timeline item.",
        "operationId": "mirror.timeline.attachments.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Adds a new attachment to a timeline item.",
        "operationId": "mirror.timeline.attachments.insert"
      }
    },
    "/timeline/{itemId}/attachments/{attachmentId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Deletes an attachment from a timeline item.",
        "operationId": "mirror.timeline.attachments.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/glass.timeline"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/glass.timeline"
            ]
          }
        ],
        "tags": [
          "timeline"
        ],
        "description": "Retrieves an attachment on a timeline item by item ID and attachment ID.",
        "operationId": "mirror.timeline.attachments.get"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/glass.location": "View your location",
        "https://www.googleapis.com/auth/glass.timeline": "View and manage your Glass timeline"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 accessCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/glass.location": "View your location",
        "https://www.googleapis.com/auth/glass.timeline": "View and manage your Glass timeline"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "accounts"
    },
    {
      "name": "contacts"
    },
    {
      "name": "locations"
    },
    {
      "name": "settings"
    },
    {
      "name": "subscriptions"
    },
    {
      "name": "timeline"
    }
  ],
  "x-components": {
  }
}