{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "Display & Video 360 API allows users to manage and create campaigns and reports.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Display & Video 360 API",
    "version": "v1dev",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "format": "google",
        "url": "https://displayvideo.googleapis.com/$discovery/rest?version=v1dev",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "displayvideo",
    "x-datafire": {
      "name": "google_displayvideo",
      "type": "openapi"
    }
  },
  "host": "displayvideo.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/download/{resourceName}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/display-video"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/display-video"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/doubleclickbidmanager"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/doubleclickbidmanager"
            ]
          }
        ],
        "tags": [
          "media"
        ],
        "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
        "operationId": "displayvideo.media.download"
      }
    },
    "/v1dev/{name}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/display-video"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/display-video"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/doubleclickbidmanager"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/doubleclickbidmanager"
            ]
          }
        ],
        "tags": [
          "sdfdownloadtasks"
        ],
        "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
        "operationId": "displayvideo.sdfdownloadtasks.operations.get"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/display-video": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports",
        "https://www.googleapis.com/auth/doubleclickbidmanager": "View and manage your reports in DoubleClick Bid Manager"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/display-video": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports",
        "https://www.googleapis.com/auth/doubleclickbidmanager": "View and manage your reports in DoubleClick Bid Manager"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "media"
    },
    {
      "name": "sdfdownloadtasks"
    }
  ],
  "x-components": {
  }
}