{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "The Google Tasks API lets you manage your tasks and task lists.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Tasks API",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "format": "google",
        "url": "https://tasks.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "tasks",
    "x-datafire": {
      "name": "google_tasks",
      "type": "openapi"
    }
  },
  "host": "tasks.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/tasks/v1/lists/{tasklist}/clear": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
        "operationId": "tasks.tasks.clear"
      }
    },
    "/tasks/v1/lists/{tasklist}/tasks": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Returns all tasks in the specified task list.",
        "operationId": "tasks.tasks.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Creates a new task on the specified task list.",
        "operationId": "tasks.tasks.insert"
      }
    },
    "/tasks/v1/lists/{tasklist}/tasks/{task}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Deletes the specified task from the task list.",
        "operationId": "tasks.tasks.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Returns the specified task.",
        "operationId": "tasks.tasks.get"
      },
      "patch": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Updates the specified task. This method supports patch semantics.",
        "operationId": "tasks.tasks.patch"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Updates the specified task.",
        "operationId": "tasks.tasks.update"
      }
    },
    "/tasks/v1/lists/{tasklist}/tasks/{task}/move": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasks"
        ],
        "description": "Moves the specified task to another position in the task list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks.",
        "operationId": "tasks.tasks.move"
      }
    },
    "/tasks/v1/users/@me/lists": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Returns all the authenticated user's task lists.",
        "operationId": "tasks.tasklists.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Creates a new task list and adds it to the authenticated user's task lists.",
        "operationId": "tasks.tasklists.insert"
      }
    },
    "/tasks/v1/users/@me/lists/{tasklist}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Deletes the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks.readonly"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Returns the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.get"
      },
      "patch": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Updates the authenticated user's specified task list. This method supports patch semantics.",
        "operationId": "tasks.tasklists.patch"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tasks"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tasks"
            ]
          }
        ],
        "tags": [
          "tasklists"
        ],
        "description": "Updates the authenticated user's specified task list.",
        "operationId": "tasks.tasklists.update"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/tasks": "Create, edit, organize, and delete all your tasks",
        "https://www.googleapis.com/auth/tasks.readonly": "View your tasks"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/tasks": "Create, edit, organize, and delete all your tasks",
        "https://www.googleapis.com/auth/tasks.readonly": "View your tasks"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "tasklists"
    },
    {
      "name": "tasks"
    }
  ],
  "x-components": {
  }
}