{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "This API allows clients to access and modify container and tag configuration.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Tag Manager API",
    "version": "v2",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "format": "google",
        "url": "https://tagmanager.googleapis.com/$discovery/rest?version=v2",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "tagmanager",
    "x-datafire": {
      "name": "google_tagmanager",
      "type": "openapi"
    }
  },
  "host": "tagmanager.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/tagmanager/v2/accounts": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.accounts"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.accounts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Accounts that a user has access to.",
        "operationId": "tagmanager.accounts.list"
      }
    },
    "/tagmanager/v2/{parent}/built_in_variables": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all the enabled Built-In Variables of a GTM Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.built_in_variables.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates one or more GTM Built-In Variables.",
        "operationId": "tagmanager.accounts.containers.workspaces.built_in_variables.create"
      }
    },
    "/tagmanager/v2/{parent}/containers": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all Containers that belongs to a GTM Account.",
        "operationId": "tagmanager.accounts.containers.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a Container.",
        "operationId": "tagmanager.accounts.containers.create"
      }
    },
    "/tagmanager/v2/{parent}/environments": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Environments of a GTM Container.",
        "operationId": "tagmanager.accounts.containers.environments.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Environment.",
        "operationId": "tagmanager.accounts.containers.environments.create"
      }
    },
    "/tagmanager/v2/{parent}/folders": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Folders of a Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.folders.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Folder.",
        "operationId": "tagmanager.accounts.containers.workspaces.folders.create"
      }
    },
    "/tagmanager/v2/{parent}/tags": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Tags of a Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.tags.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Tag.",
        "operationId": "tagmanager.accounts.containers.workspaces.tags.create"
      }
    },
    "/tagmanager/v2/{parent}/templates": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Templates of a GTM container workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.templates.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Custom Template.",
        "operationId": "tagmanager.accounts.containers.workspaces.templates.create"
      }
    },
    "/tagmanager/v2/{parent}/triggers": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Triggers of a Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.triggers.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Trigger.",
        "operationId": "tagmanager.accounts.containers.workspaces.triggers.create"
      }
    },
    "/tagmanager/v2/{parent}/user_permissions": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "List all users that have access to the account along with Account and Container user access granted to each of them.",
        "operationId": "tagmanager.accounts.user_permissions.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a user's Account & Container access.",
        "operationId": "tagmanager.accounts.user_permissions.create"
      }
    },
    "/tagmanager/v2/{parent}/variables": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Variables of a Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.variables.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Variable.",
        "operationId": "tagmanager.accounts.containers.workspaces.variables.create"
      }
    },
    "/tagmanager/v2/{parent}/version_headers": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all Container Versions of a GTM Container.",
        "operationId": "tagmanager.accounts.containers.version_headers.list"
      }
    },
    "/tagmanager/v2/{parent}/version_headers:latest": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Gets the latest container version header",
        "operationId": "tagmanager.accounts.containers.version_headers.latest"
      }
    },
    "/tagmanager/v2/{parent}/versions:live": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Gets the live (i.e. published) container version",
        "operationId": "tagmanager.accounts.containers.versions.live"
      }
    },
    "/tagmanager/v2/{parent}/workspaces": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all Workspaces that belong to a GTM Container.",
        "operationId": "tagmanager.accounts.containers.workspaces.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a Workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.create"
      }
    },
    "/tagmanager/v2/{parent}/zones": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Lists all GTM Zones of a GTM container workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.zones.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a GTM Zone.",
        "operationId": "tagmanager.accounts.containers.workspaces.zones.create"
      }
    },
    "/tagmanager/v2/{path}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Removes a user from the account, revoking access to it and all of its containers.",
        "operationId": "tagmanager.accounts.user_permissions.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Gets a user's Account & Container access.",
        "operationId": "tagmanager.accounts.user_permissions.get"
      },
      "put": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.manage.users"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Updates a user's Account & Container access.",
        "operationId": "tagmanager.accounts.user_permissions.update"
      }
    },
    "/tagmanager/v2/{path}/built_in_variables:revert": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Reverts changes to a GTM Built-In Variables in a GTM Workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.built_in_variables.revert"
      }
    },
    "/tagmanager/v2/{path}/status": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Finds conflicting and modified entities in the workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.getStatus"
      }
    },
    "/tagmanager/v2/{path}:create_version": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Creates a Container Version from the entities present in the workspace, deletes the workspace, and sets the base container version to the newly created version.",
        "operationId": "tagmanager.accounts.containers.workspaces.create_version"
      }
    },
    "/tagmanager/v2/{path}:entities": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.readonly"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "List all entities in a GTM Folder.",
        "operationId": "tagmanager.accounts.containers.workspaces.folders.entities"
      }
    },
    "/tagmanager/v2/{path}:move_entities_to_folder": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Moves entities to a GTM Folder.",
        "operationId": "tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder"
      }
    },
    "/tagmanager/v2/{path}:publish": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.publish"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.publish"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Publishes a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.publish"
      }
    },
    "/tagmanager/v2/{path}:quick_preview": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Quick previews a workspace by creating a fake container version from all entities in the provided workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.quick_preview"
      }
    },
    "/tagmanager/v2/{path}:reauthorize": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.publish"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.publish"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Re-generates the authorization code for a GTM Environment.",
        "operationId": "tagmanager.accounts.containers.environments.reauthorize"
      }
    },
    "/tagmanager/v2/{path}:resolve_conflict": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Resolves a merge conflict for a workspace entity by updating it to the resolved entity passed in the request.",
        "operationId": "tagmanager.accounts.containers.workspaces.resolve_conflict"
      }
    },
    "/tagmanager/v2/{path}:revert": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Reverts changes to a GTM Zone in a GTM Workspace.",
        "operationId": "tagmanager.accounts.containers.workspaces.zones.revert"
      }
    },
    "/tagmanager/v2/{path}:set_latest": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Sets the latest version used for synchronization of workspaces when detecting conflicts and errors.",
        "operationId": "tagmanager.accounts.containers.versions.set_latest"
      }
    },
    "/tagmanager/v2/{path}:sync": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containers"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Syncs a workspace to the latest container version by updating all unmodified workspace entities and displaying conflicts for modified entities.",
        "operationId": "tagmanager.accounts.containers.workspaces.sync"
      }
    },
    "/tagmanager/v2/{path}:undelete": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
            ]
          }
        ],
        "tags": [
          "accounts"
        ],
        "description": "Undeletes a Container Version.",
        "operationId": "tagmanager.accounts.containers.versions.undelete"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.delete.containers": "Delete your Google Tag Manager containers",
        "https://www.googleapis.com/auth/tagmanager.edit.containers": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing",
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": "Manage your Google Tag Manager container versions",
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": "View and manage your Google Tag Manager accounts",
        "https://www.googleapis.com/auth/tagmanager.manage.users": "Manage user permissions of your Google Tag Manager account and container",
        "https://www.googleapis.com/auth/tagmanager.publish": "Publish your Google Tag Manager container versions",
        "https://www.googleapis.com/auth/tagmanager.readonly": "View your Google Tag Manager container and its subcomponents"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.delete.containers": "Delete your Google Tag Manager containers",
        "https://www.googleapis.com/auth/tagmanager.edit.containers": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing",
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": "Manage your Google Tag Manager container versions",
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": "View and manage your Google Tag Manager accounts",
        "https://www.googleapis.com/auth/tagmanager.manage.users": "Manage user permissions of your Google Tag Manager account and container",
        "https://www.googleapis.com/auth/tagmanager.publish": "Publish your Google Tag Manager container versions",
        "https://www.googleapis.com/auth/tagmanager.readonly": "View your Google Tag Manager container and its subcomponents"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "accounts"
    }
  ],
  "x-components": {
  }
}