{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "genomics.googleapis.com",
  "basePath": "/",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Upload, process, query, and search Genomics data in the cloud.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Genomics",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.0.1"
        },
        "format": "google",
        "url": "https://genomics.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "genomics",
    "x-datafire": {
      "name": "google_genomics",
      "type": "openapi"
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/bigquery": "View and manage your data in Google BigQuery",
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/devstorage.read_write": "Manage your data in Google Cloud Storage",
        "https://www.googleapis.com/auth/genomics": "View and manage Genomics data",
        "https://www.googleapis.com/auth/genomics.readonly": "View Genomics data"
      },
      "type": "oauth2"
    },
    "offline": {
      "type": "oauth2",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/bigquery": "View and manage your data in Google BigQuery",
        "https://www.googleapis.com/auth/cloud-platform": "View and manage your data across Google Cloud Platform services",
        "https://www.googleapis.com/auth/devstorage.read_write": "Manage your data in Google Cloud Storage",
        "https://www.googleapis.com/auth/genomics": "View and manage Genomics data",
        "https://www.googleapis.com/auth/genomics.readonly": "View Genomics data"
      },
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "description": "Allows offline access using a refresh_token"
    }
  },
  "tags": [
    {
      "name": "annotations"
    },
    {
      "name": "annotationsets"
    },
    {
      "name": "callsets"
    },
    {
      "name": "datasets"
    },
    {
      "name": "operations"
    },
    {
      "name": "readgroupsets"
    },
    {
      "name": "reads"
    },
    {
      "name": "references"
    },
    {
      "name": "referencesets"
    },
    {
      "name": "variants"
    },
    {
      "name": "variantsets"
    }
  ],
  "paths": {
    "/v1/annotations": {
      "post": {
        "description": "Creates a new annotation. Caller must have WRITE permission\nfor the associated annotation set.\n\nThe following fields are required:\n\n* annotationSetId\n* referenceName or\n  referenceId\n\n### Transcripts\n\nFor annotations of type TRANSCRIPT, the following fields of\ntranscript must be provided:\n\n* exons.start\n* exons.end\n\nAll other fields may be optionally specified, unless documented as being\nserver-generated (for example, the `id` field). The annotated\nrang[...]",
        "operationId": "annotations.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/v1/annotations/search": {
      "post": {
        "description": "Searches for annotations that match the given criteria. Results are\nordered by genomic coordinate (by reference sequence, then position).\nAnnotations with equivalent genomic coordinates are returned in an\nunspecified order. This order is consistent, such that two queries for the\nsame content (regardless of page size) yield annotations in the same order\nacross their respective streams of paginated responses. Caller must have\nREAD permission for the queried annotation[...]",
        "operationId": "annotations.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/v1/annotations/{annotationId}": {
      "delete": {
        "description": "Deletes an annotation. Caller must have WRITE permission for\nthe associated annotation set.",
        "operationId": "annotations.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      },
      "get": {
        "description": "Gets an annotation. Caller must have READ permission\nfor the associated annotation set.",
        "operationId": "annotations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      },
      "put": {
        "description": "Updates an annotation. Caller must have\nWRITE permission for the associated dataset.",
        "operationId": "annotations.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/v1/annotations:batchCreate": {
      "post": {
        "description": "Creates one or more new annotations atomically. All annotations must\nbelong to the same annotation set. Caller must have WRITE\npermission for this annotation set. For optimal performance, batch\npositionally adjacent annotations together.\n\nIf the request has a systemic issue, such as an attempt to write to\nan inaccessible annotation set, the entire RPC will fail accordingly. For\nlesser data issues, when possible an error will be isolated to the\ncorresponding batch [...]",
        "operationId": "annotations.batchCreate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotations"
        ]
      }
    },
    "/v1/annotationsets": {
      "post": {
        "description": "Creates a new annotation set. Caller must have WRITE permission for the\nassociated dataset.\n\nThe following fields are required:\n\n  * datasetId\n  * referenceSetId\n\nAll other fields may be optionally specified, unless documented as being\nserver-generated (for example, the `id` field).",
        "operationId": "annotationsets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationsets"
        ]
      }
    },
    "/v1/annotationsets/search": {
      "post": {
        "description": "Searches for annotation sets that match the given criteria. Annotation sets\nare returned in an unspecified order. This order is consistent, such that\ntwo queries for the same content (regardless of page size) yield annotation\nsets in the same order across their respective streams of paginated\nresponses. Caller must have READ permission for the queried datasets.",
        "operationId": "annotationsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotationsets"
        ]
      }
    },
    "/v1/annotationsets/{annotationSetId}": {
      "delete": {
        "description": "Deletes an annotation set. Caller must have WRITE permission\nfor the associated annotation set.",
        "operationId": "annotationsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationsets"
        ]
      },
      "get": {
        "description": "Gets an annotation set. Caller must have READ permission for\nthe associated dataset.",
        "operationId": "annotationsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "annotationsets"
        ]
      },
      "put": {
        "description": "Updates an annotation set. The update must respect all mutability\nrestrictions and other invariants described on the annotation set resource.\nCaller must have WRITE permission for the associated dataset.",
        "operationId": "annotationsets.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "annotationsets"
        ]
      }
    },
    "/v1/callsets": {
      "post": {
        "description": "Creates a new call set.\n\nFor the definitions of call sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "callsets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/v1/callsets/search": {
      "post": {
        "description": "Gets a list of call sets matching the criteria.\n\nFor the definitions of call sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchCallSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L178).",
        "operationId": "callsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/v1/callsets/{callSetId}": {
      "delete": {
        "description": "Deletes a call set.\n\nFor the definitions of call sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "callsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      },
      "get": {
        "description": "Gets a call set by ID.\n\nFor the definitions of call sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "callsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      },
      "patch": {
        "description": "Updates a call set.\n\nFor the definitions of call sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThis method supports patch semantics.",
        "operationId": "callsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "callsets"
        ]
      }
    },
    "/v1/datasets": {
      "get": {
        "description": "Lists datasets within a project.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "post": {
        "description": "Creates a new dataset.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/v1/datasets/{datasetId}": {
      "delete": {
        "description": "Deletes a dataset and all of its contents (all read group sets,\nreference sets, variant sets, call sets, annotation sets, etc.)\nThis is reversible (up to one week after the deletion) via\nthe\ndatasets.undelete\noperation.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "get": {
        "description": "Gets a dataset by ID.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      },
      "patch": {
        "description": "Updates a dataset.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThis method supports patch semantics.",
        "operationId": "datasets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/v1/datasets/{datasetId}:undelete": {
      "post": {
        "description": "Undeletes a dataset by restoring a dataset which was deleted via this API.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThis operation is only possible for a week after the deletion occurred.",
        "operationId": "datasets.undelete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/v1/readgroupsets/search": {
      "post": {
        "description": "Searches for read group sets matching the criteria.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchReadGroupSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/readmethods.avdl#L135).",
        "operationId": "readgroupsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/v1/readgroupsets/{readGroupSetId}": {
      "delete": {
        "description": "Deletes a read group set.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "readgroupsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      },
      "get": {
        "description": "Gets a read group set by ID.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "readgroupsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      },
      "patch": {
        "description": "Updates a read group set.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThis method supports patch semantics.",
        "operationId": "readgroupsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/v1/readgroupsets/{readGroupSetId}/coveragebuckets": {
      "get": {
        "description": "Lists fixed width coverage buckets for a read group set, each of which\ncorrespond to a range of a reference sequence. Each bucket summarizes\ncoverage information across its corresponding genomic range.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nCoverage is defined as the number of reads which are aligned to a given\nbase in the refer[...]",
        "operationId": "readgroupsets.coveragebuckets.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/v1/readgroupsets/{readGroupSetId}:export": {
      "post": {
        "description": "Exports a read group set to a BAM file in Google Cloud Storage.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nNote that currently there may be some differences between exported BAM\nfiles and the original BAM file at the time of import. See\nImportReadGroupSets\nfor caveats.",
        "operationId": "readgroupsets.export",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/devstorage.read_write"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/v1/readgroupsets:import": {
      "post": {
        "description": "Creates read group sets by asynchronously importing the provided\ninformation.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThe caller must have WRITE permissions to the dataset.\n\n## Notes on [BAM](https://samtools.github.io/hts-specs/SAMv1.pdf) import\n\n- Tags will be converted to strings - tag types are not preserved\n- Comments (`@[...]",
        "operationId": "readgroupsets.import",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/devstorage.read_write"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "readgroupsets"
        ]
      }
    },
    "/v1/reads/search": {
      "post": {
        "description": "Gets a list of reads for one or more read group sets.\n\nFor the definitions of read group sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nReads search operates over a genomic coordinate space of reference sequence\n& position defined over the reference sequences to which the requested\nread group sets are aligned.\n\nIf a target positional range is specified, search returns a[...]",
        "operationId": "reads.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "reads"
        ]
      }
    },
    "/v1/references/search": {
      "post": {
        "description": "Searches for references which match the given criteria.\n\nFor the definitions of references and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchReferences](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L146).",
        "operationId": "references.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/v1/references/{referenceId}": {
      "get": {
        "description": "Gets a reference.\n\nFor the definitions of references and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.getReference](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L158).",
        "operationId": "references.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/v1/references/{referenceId}/bases": {
      "get": {
        "description": "Lists the bases in a reference, optionally restricted to a range.\n\nFor the definitions of references and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.getReferenceBases](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L221).",
        "operationId": "references.bases.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "references"
        ]
      }
    },
    "/v1/referencesets/search": {
      "post": {
        "description": "Searches for reference sets which match the given criteria.\n\nFor the definitions of references and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchReferenceSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L71)",
        "operationId": "referencesets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "referencesets"
        ]
      }
    },
    "/v1/referencesets/{referenceSetId}": {
      "get": {
        "description": "Gets a reference set.\n\nFor the definitions of references and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.getReferenceSet](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/referencemethods.avdl#L83).",
        "operationId": "referencesets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "referencesets"
        ]
      }
    },
    "/v1/variants": {
      "post": {
        "description": "Creates a new variant.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variants.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/v1/variants/search": {
      "post": {
        "description": "Gets a list of variants matching the criteria.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchVariants](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L126).",
        "operationId": "variants.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/v1/variants/{variantId}": {
      "delete": {
        "description": "Deletes a variant.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variants.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      },
      "get": {
        "description": "Gets a variant by ID.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variants.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      },
      "patch": {
        "description": "Updates a variant.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThis method supports patch semantics. Returns the modified variant without\nits calls.",
        "operationId": "variants.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/v1/variants:import": {
      "post": {
        "description": "Creates variant data by asynchronously importing the provided information.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThe variants for import will be merged with any existing variant that\nmatches its reference sequence, start, end, reference bases, and\nalternative bases. If no such variant exists, a new one will be created.\n\nWhen vari[...]",
        "operationId": "variants.import",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/devstorage.read_write"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/v1/variants:merge": {
      "post": {
        "description": "Merges the given variants with existing variants.\n\nFor the definitions of variants and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nEach variant will be\nmerged with an existing variant that matches its reference sequence,\nstart, end, reference bases, and alternative bases. If no such variant\nexists, a new one will be created.\n\nWhen variants are merged, the call information fr[...]",
        "operationId": "variants.merge",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variants"
        ]
      }
    },
    "/v1/variantsets": {
      "post": {
        "description": "Creates a new variant set.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nThe provided variant set must have a valid `datasetId` set - all other\nfields are optional. Note that the `id` field will be ignored, as this is\nassigned by the server.",
        "operationId": "variantsets.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/v1/variantsets/search": {
      "post": {
        "description": "Returns a list of all variant sets matching search criteria.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nImplements\n[GlobalAllianceApi.searchVariantSets](https://github.com/ga4gh/schemas/blob/v0.5.1/src/main/resources/avro/variantmethods.avdl#L49).",
        "operationId": "variantsets.search",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/v1/variantsets/{variantSetId}": {
      "delete": {
        "description": "Deletes a variant set including all variants, call sets, and calls within.\nThis is not reversible.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variantsets.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      },
      "get": {
        "description": "Gets a variant set by ID.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variantsets.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics.readonly"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      },
      "patch": {
        "description": "Updates a variant set using patch semantics.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variantsets.patch",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/v1/variantsets/{variantSetId}:export": {
      "post": {
        "description": "Exports variant set data to an external destination.\n\nFor the definitions of variant sets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "variantsets.export",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/bigquery"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "variantsets"
        ]
      }
    },
    "/v1/{name}": {
      "get": {
        "description": "Gets the latest state of a long-running operation.  Clients can use this\nmethod to poll the operation result at intervals as recommended by the API\nservice.",
        "operationId": "operations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "operations"
        ]
      }
    },
    "/v1/{name}:cancel": {
      "post": {
        "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. Clients may use Operations.GetOperation or Operations.ListOperations to check whether the cancellation succeeded or the operation completed despite cancellation.",
        "operationId": "operations.cancel",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "operations"
        ]
      }
    },
    "/v1/{resource}:getIamPolicy": {
      "post": {
        "description": "Gets the access control policy for the dataset. This is empty if the\npolicy or resource does not exist.\n\nSee <a href=\"/iam/docs/managing-policies#getting_a_policy\">Getting a\nPolicy</a> for more information.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.getIamPolicy",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/v1/{resource}:setIamPolicy": {
      "post": {
        "description": "Sets the access control policy on the specified dataset. Replaces any\nexisting policy.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)\n\nSee <a href=\"/iam/docs/managing-policies#setting_a_policy\">Setting a\nPolicy</a> for more information.",
        "operationId": "datasets.setIamPolicy",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    },
    "/v1/{resource}:testIamPermissions": {
      "post": {
        "description": "Returns permissions that a caller has on the specified resource.\nSee <a href=\"/iam/docs/managing-policies#testing_permissions\">Testing\nPermissions</a> for more information.\n\nFor the definitions of datasets and other genomics resources, see\n[Fundamentals of Google\nGenomics](https://cloud.google.com/genomics/fundamentals-of-google-genomics)",
        "operationId": "datasets.testIamPermissions",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/cloud-platform"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/genomics"
            ]
          }
        ],
        "tags": [
          "datasets"
        ]
      }
    }
  }
}