{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "slides.googleapis.com",
  "basePath": "/",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "An API for creating and editing Google Slides presentations.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Slides",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "cloud"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.6.0"
        },
        "format": "google",
        "url": "https://slides.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "slides",
    "x-datafire": {
      "name": "google_slides",
      "type": "openapi"
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/drive.file": "View and manage Google Drive files and folders that you have opened or created with this app",
        "https://www.googleapis.com/auth/drive.readonly": "View the files in your Google Drive",
        "https://www.googleapis.com/auth/presentations": "View and manage your Google Slides presentations",
        "https://www.googleapis.com/auth/presentations.readonly": "View your Google Slides presentations",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/spreadsheets.readonly": "View your Google Spreadsheets"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 accessCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/drive.file": "View and manage Google Drive files and folders that you have opened or created with this app",
        "https://www.googleapis.com/auth/drive.readonly": "View the files in your Google Drive",
        "https://www.googleapis.com/auth/presentations": "View and manage your Google Slides presentations",
        "https://www.googleapis.com/auth/presentations.readonly": "View your Google Slides presentations",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/spreadsheets.readonly": "View your Google Spreadsheets"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    },
    "offline": {
      "type": "oauth2",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/drive": "View and manage the files in your Google Drive",
        "https://www.googleapis.com/auth/drive.file": "View and manage Google Drive files and folders that you have opened or created with this app",
        "https://www.googleapis.com/auth/drive.readonly": "View the files in your Google Drive",
        "https://www.googleapis.com/auth/presentations": "View and manage your Google Slides presentations",
        "https://www.googleapis.com/auth/presentations.readonly": "View your Google Slides presentations",
        "https://www.googleapis.com/auth/spreadsheets": "View and manage your spreadsheets in Google Drive",
        "https://www.googleapis.com/auth/spreadsheets.readonly": "View your Google Spreadsheets"
      },
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "description": "Allows offline access using a refresh_token"
    }
  },
  "tags": [
    {
      "name": "presentations"
    }
  ],
  "paths": {
    "/v1/presentations": {
      "post": {
        "description": "Creates a new presentation using the title given in the request. Other\nfields in the request are ignored.\nReturns the created presentation.",
        "operationId": "presentations.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations"
            ]
          }
        ],
        "tags": [
          "presentations"
        ]
      }
    },
    "/v1/presentations/{presentationId}": {
      "get": {
        "description": "Gets the latest version of the specified presentation.",
        "operationId": "presentations.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ]
          }
        ],
        "tags": [
          "presentations"
        ]
      }
    },
    "/v1/presentations/{presentationId}/pages/{pageObjectId}": {
      "get": {
        "description": "Gets the latest version of the specified page in the presentation.",
        "operationId": "presentations.pages.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ]
          }
        ],
        "tags": [
          "presentations"
        ]
      }
    },
    "/v1/presentations/{presentationId}/pages/{pageObjectId}/thumbnail": {
      "get": {
        "description": "Generates a thumbnail of the latest version of the specified page in the\npresentation and returns a URL to the thumbnail image.\n\nThis request counts as an expensive read request for quota purposes.",
        "operationId": "presentations.pages.getThumbnail",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations.readonly"
            ]
          }
        ],
        "tags": [
          "presentations"
        ]
      }
    },
    "/v1/presentations/{presentationId}:batchUpdate": {
      "post": {
        "description": "Applies one or more updates to the presentation.\n\nEach request is validated before\nbeing applied. If any request is not valid, then the entire request will\nfail and nothing will be applied.\n\nSome requests have replies to\ngive you some information about how they are applied. Other requests do\nnot need to return information; these each return an empty reply.\nThe order of replies matches that of the requests.\n\nFor example, suppose you call batchUpdate with four up[...]",
        "operationId": "presentations.batchUpdate",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.file"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.file"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/presentations"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/presentations"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/spreadsheets"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/spreadsheets"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/spreadsheets.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/spreadsheets.readonly"
            ]
          }
        ],
        "tags": [
          "presentations"
        ]
      }
    }
  }
}