{
  "swagger": "2.0",
  "schemes": [
    "https"
  ],
  "host": "people.googleapis.com",
  "basePath": "/",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com"
    },
    "description": "Provides access to information about profiles and contacts.",
    "title": "People",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "social"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.6.2"
        },
        "format": "google",
        "url": "https://people.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "people",
    "x-datafire": {
      "name": "google_people",
      "type": "openapi"
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/contacts": "Manage your contacts",
        "https://www.googleapis.com/auth/contacts.readonly": "View your contacts",
        "https://www.googleapis.com/auth/plus.login": "Know the list of people in your circles, your age range, and language",
        "https://www.googleapis.com/auth/user.addresses.read": "View your street addresses",
        "https://www.googleapis.com/auth/user.birthday.read": "View your complete date of birth",
        "https://www.googleapis.com/auth/user.emails.read": "View your email addresses",
        "https://www.googleapis.com/auth/user.phonenumbers.read": "View your phone numbers",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address",
        "https://www.googleapis.com/auth/userinfo.profile": "View your basic profile info"
      },
      "type": "oauth2"
    },
    "offline": {
      "type": "oauth2",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/contacts": "Manage your contacts",
        "https://www.googleapis.com/auth/contacts.readonly": "View your contacts",
        "https://www.googleapis.com/auth/plus.login": "Know the list of people in your circles, your age range, and language",
        "https://www.googleapis.com/auth/user.addresses.read": "View your street addresses",
        "https://www.googleapis.com/auth/user.birthday.read": "View your complete date of birth",
        "https://www.googleapis.com/auth/user.emails.read": "View your email addresses",
        "https://www.googleapis.com/auth/user.phonenumbers.read": "View your phone numbers",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address",
        "https://www.googleapis.com/auth/userinfo.profile": "View your basic profile info"
      },
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
      "description": "Allows offline access using a refresh_token"
    }
  },
  "tags": [
    {
      "name": "contactGroups"
    },
    {
      "name": "people"
    }
  ],
  "paths": {
    "/v1/contactGroups": {
      "get": {
        "description": "List all contact groups owned by the authenticated user. Members of the\ncontact groups are not populated.",
        "operationId": "contactGroups.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      },
      "post": {
        "description": "Create a new contact group owned by the authenticated user.",
        "operationId": "contactGroups.create",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/contactGroups:batchGet": {
      "get": {
        "description": "Get a list of contact groups owned by the authenticated user by specifying\na list of contact group resource names.",
        "operationId": "contactGroups.batchGet",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/people:batchGet": {
      "get": {
        "description": "Provides information about a list of specific people by specifying a list\nof requested resource names. Use `people/me` to indicate the authenticated\nuser.\n<br>\nThe request throws a 400 error if 'personFields' is not specified.",
        "operationId": "people.getBatchGet",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.login"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.emails.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/people:createContact": {
      "post": {
        "description": "Create a new contact and return the person resource for that contact.",
        "operationId": "people.createContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}": {
      "delete": {
        "description": "Delete an existing contact group owned by the authenticated user by\nspecifying a contact group resource name.",
        "operationId": "contactGroups.delete",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      },
      "get": {
        "description": "Get a specific contact group owned by the authenticated user by specifying\na contact group resource name.",
        "operationId": "contactGroups.get",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.login"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.addresses.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.birthday.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.emails.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/user.phonenumbers.read"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.profile"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      },
      "put": {
        "description": "Update the name of an existing contact group owned by the authenticated\nuser.",
        "operationId": "contactGroups.update",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/{resourceName}/connections": {
      "get": {
        "description": "Provides a list of the authenticated user's contacts merged with any\nconnected profiles.\n<br>\nThe request throws a 400 error if 'personFields' is not specified.",
        "operationId": "people.connections.list",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts.readonly"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}/members:modify": {
      "post": {
        "description": "Modify the members of a contact group owned by the authenticated user.",
        "operationId": "contactGroups.members.modify",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "contactGroups"
        ]
      }
    },
    "/v1/{resourceName}:deleteContact": {
      "delete": {
        "description": "Delete a contact person. Any non-contact data will not be deleted.",
        "operationId": "people.deleteContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    },
    "/v1/{resourceName}:updateContact": {
      "patch": {
        "description": "Update contact data for an existing contact person. Any non-contact data\nwill not be modified.\n\nThe request throws a 400 error if `updatePersonFields` is not specified.\n<br>\nThe request throws a 400 error if `person.metadata.sources` is not\nspecified for the contact to be updated.\n<br>\nThe request throws a 412 error if `person.metadata.sources.etag` is\ndifferent than the contact's etag, which indicates the contact has changed\nsince its data was read. Clients sho[...]",
        "operationId": "people.updateContact",
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/contacts"
            ]
          }
        ],
        "tags": [
          "people"
        ]
      }
    }
  }
}