{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "YouTube Reporting API",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "converter": {
          "url": "https://github.com/lucybot/api-spec-converter",
          "version": "2.7.31"
        },
        "format": "google",
        "url": "https://youtubereporting.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "youtubereporting",
    "x-datafire": {
      "name": "google_youtubereporting",
      "type": "openapi"
    }
  },
  "host": "youtubereporting.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v1/jobs": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Lists jobs.",
        "operationId": "youtubereporting.jobs.list"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Creates a job and returns it.",
        "operationId": "youtubereporting.jobs.create"
      }
    },
    "/v1/jobs/{jobId}": {
      "delete": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Deletes a job.",
        "operationId": "youtubereporting.jobs.delete"
      },
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Gets a job.",
        "operationId": "youtubereporting.jobs.get"
      }
    },
    "/v1/jobs/{jobId}/reports": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist.",
        "operationId": "youtubereporting.jobs.reports.list"
      }
    },
    "/v1/jobs/{jobId}/reports/{reportId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "jobs"
        ],
        "description": "Gets the metadata of a specific report.",
        "operationId": "youtubereporting.jobs.reports.get"
      }
    },
    "/v1/media/{resourceName}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "media"
        ],
        "description": "Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`.",
        "operationId": "youtubereporting.media.download"
      }
    },
    "/v1/reportTypes": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics-monetary.readonly"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/yt-analytics.readonly"
            ]
          }
        ],
        "tags": [
          "reportTypes"
        ],
        "description": "Lists report types.",
        "operationId": "youtubereporting.reportTypes.list"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": "View monetary and non-monetary YouTube Analytics reports for your YouTube content",
        "https://www.googleapis.com/auth/yt-analytics.readonly": "View YouTube Analytics reports for your YouTube content"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": "View monetary and non-monetary YouTube Analytics reports for your YouTube content",
        "https://www.googleapis.com/auth/yt-analytics.readonly": "View YouTube Analytics reports for your YouTube content"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "jobs"
    },
    {
      "name": "media"
    },
    {
      "name": "reportTypes"
    }
  ],
  "x-components": {
  }
}