{
  "swagger": "2.0",
  "info": {
    "contact": {
      "name": "Google",
      "url": "https://google.com",
      "x-twitter": "youtube"
    },
    "description": "The Google Play games service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
    "license": {
      "name": "Creative Commons Attribution 3.0",
      "url": "http://creativecommons.org/licenses/by/3.0/"
    },
    "termsOfService": "https://developers.google.com/terms/",
    "title": "Google Play Game Services",
    "version": "v1",
    "x-apiClientRegistration": {
      "url": "https://console.developers.google.com"
    },
    "x-apisguru-categories": [
      "analytics",
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png"
    },
    "x-origin": [
      {
        "format": "google",
        "url": "https://games.googleapis.com/$discovery/rest?version=v1",
        "version": "v1"
      }
    ],
    "x-preferred": true,
    "x-providerName": "googleapis.com",
    "x-serviceName": "games",
    "x-datafire": {
      "name": "google_games",
      "type": "openapi"
    }
  },
  "host": "games.googleapis.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/games/v1/achievements": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievementDefinitions"
        ],
        "description": "Lists all the achievement definitions for your application.",
        "operationId": "games.achievementDefinitions.list"
      }
    },
    "/games/v1/achievements/updateMultiple": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Updates multiple achievements for the currently authenticated player.",
        "operationId": "games.achievements.updateMultiple"
      }
    },
    "/games/v1/achievements/{achievementId}/increment": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
        "operationId": "games.achievements.increment"
      }
    },
    "/games/v1/achievements/{achievementId}/reveal": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
        "operationId": "games.achievements.reveal"
      }
    },
    "/games/v1/achievements/{achievementId}/setStepsAtLeast": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
        "operationId": "games.achievements.setStepsAtLeast"
      }
    },
    "/games/v1/achievements/{achievementId}/unlock": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Unlocks this achievement for the currently authenticated player.",
        "operationId": "games.achievements.unlock"
      }
    },
    "/games/v1/applications/getEndPoint": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Returns a URL for the requested end point type.",
        "operationId": "games.applications.getEndPoint"
      }
    },
    "/games/v1/applications/played": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Indicate that the currently authenticated user is playing your application.",
        "operationId": "games.applications.played"
      }
    },
    "/games/v1/applications/{applicationId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
        "operationId": "games.applications.get"
      }
    },
    "/games/v1/applications/{applicationId}/verify": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "applications"
        ],
        "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
        "operationId": "games.applications.verify"
      }
    },
    "/games/v1/eventDefinitions": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "events"
        ],
        "description": "Returns a list of the event definitions in this application.",
        "operationId": "games.events.listDefinitions"
      }
    },
    "/games/v1/events": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "events"
        ],
        "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
        "operationId": "games.events.listByPlayer"
      },
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "events"
        ],
        "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
        "operationId": "games.events.record"
      }
    },
    "/games/v1/leaderboards": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "leaderboards"
        ],
        "description": "Lists all the leaderboard metadata for your application.",
        "operationId": "games.leaderboards.list"
      }
    },
    "/games/v1/leaderboards/scores": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "scores"
        ],
        "description": "Submits multiple scores to leaderboards.",
        "operationId": "games.scores.submitMultiple"
      }
    },
    "/games/v1/leaderboards/{leaderboardId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "leaderboards"
        ],
        "description": "Retrieves the metadata of the leaderboard with the given ID.",
        "operationId": "games.leaderboards.get"
      }
    },
    "/games/v1/leaderboards/{leaderboardId}/scores": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "scores"
        ],
        "description": "Submits a score to the specified leaderboard.",
        "operationId": "games.scores.submit"
      }
    },
    "/games/v1/leaderboards/{leaderboardId}/scores/{collection}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "scores"
        ],
        "description": "Lists the scores in a leaderboard, starting from the top.",
        "operationId": "games.scores.list"
      }
    },
    "/games/v1/leaderboards/{leaderboardId}/window/{collection}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "scores"
        ],
        "description": "Lists the scores in a leaderboard around (and including) a player's score.",
        "operationId": "games.scores.listWindow"
      }
    },
    "/games/v1/metagameConfig": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "metagame"
        ],
        "description": "Return the metagame configuration data for the calling application.",
        "operationId": "games.metagame.getMetagameConfig"
      }
    },
    "/games/v1/players/me/players/{collection}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "players"
        ],
        "description": "Get the collection of players for the currently authenticated user.",
        "operationId": "games.players.list"
      }
    },
    "/games/v1/players/{playerId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "players"
        ],
        "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
        "operationId": "games.players.get"
      }
    },
    "/games/v1/players/{playerId}/achievements": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "achievements"
        ],
        "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
        "operationId": "games.achievements.list"
      }
    },
    "/games/v1/players/{playerId}/categories/{collection}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "metagame"
        ],
        "description": "List play data aggregated per category for the player corresponding to `playerId`.",
        "operationId": "games.metagame.listCategoriesByPlayer"
      }
    },
    "/games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "scores"
        ],
        "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
        "operationId": "games.scores.get"
      }
    },
    "/games/v1/players/{playerId}/snapshots": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "snapshots"
        ],
        "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
        "operationId": "games.snapshots.list"
      }
    },
    "/games/v1/revisions/check": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "revisions"
        ],
        "description": "Checks whether the games client is out of date.",
        "operationId": "games.revisions.check"
      }
    },
    "/games/v1/snapshots/{snapshotId}": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "snapshots"
        ],
        "description": "Retrieves the metadata for a given snapshot ID.",
        "operationId": "games.snapshots.get"
      }
    },
    "/games/v1/snapshotsExtended/{snapshotName}:resolveHead": {
      "post": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/drive.appdata"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/drive.appdata"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "snapshotsExtended"
        ],
        "description": "Resolves any potential conflicts according to the resolution policy specified in the request and returns the snapshot head after the resolution.",
        "operationId": "games.snapshotsExtended.resolveSnapshotHead"
      }
    },
    "/games/v1/stats": {
      "get": {
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/games"
            ],
            "Oauth2c": [
              "https://www.googleapis.com/auth/games"
            ]
          }
        ],
        "tags": [
          "stats"
        ],
        "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
        "operationId": "games.stats.get"
      }
    }
  },
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 implicit authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": "View and manage its own configuration data in your Google Drive",
        "https://www.googleapis.com/auth/games": "Create, edit, and delete your Google Play Games activity"
      },
      "type": "oauth2"
    },
    "Oauth2c": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authorizationCode authentication",
      "flow": "accessCode",
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": "View and manage its own configuration data in your Google Drive",
        "https://www.googleapis.com/auth/games": "Create, edit, and delete your Google Play Games activity"
      },
      "tokenUrl": "https://accounts.google.com/o/oauth2/token",
      "type": "oauth2"
    }
  },
  "tags": [
    {
      "name": "achievementDefinitions"
    },
    {
      "name": "achievements"
    },
    {
      "name": "applications"
    },
    {
      "name": "events"
    },
    {
      "name": "leaderboards"
    },
    {
      "name": "metagame"
    },
    {
      "name": "players"
    },
    {
      "name": "revisions"
    },
    {
      "name": "scores"
    },
    {
      "name": "snapshots"
    },
    {
      "name": "snapshotsExtended"
    },
    {
      "name": "stats"
    }
  ],
  "x-components": {
  }
}