{
  "swagger": "2.0",
  "info": {
    "contact": {
      "x-twitter": "Shutterstock"
    },
    "description": "The Shutterstock API provides access to Shutterstock's library of media, as well as information about customers' accounts and the contributors that provide the media.",
    "title": "Shutterstock API Explorer",
    "version": "1.0.16",
    "x-apisguru-categories": [
      "media"
    ],
    "x-logo": {
      "url": "https://api.apis.guru/v2/cache/logo/https_twitter.com_Shutterstock_profile_image.jpeg"
    },
    "x-origin": [
      {
        "format": "openapi",
        "url": "https://api-explorer.shutterstock.com/openapi.json",
        "version": "3.0"
      }
    ],
    "x-preferred": true,
    "x-providerName": "shutterstock.com",
    "x-datafire": {
      "name": "shutterstock",
      "type": "openapi"
    }
  },
  "host": "api.shutterstock.com",
  "basePath": "/",
  "schemes": [
    "https"
  ],
  "paths": {
    "/v2/audio": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint lists information about one or more audio tracks, including the description and publication date.",
        "operationId": "getTrackList",
        "summary": "List audio tracks"
      }
    },
    "/v2/audio/collections": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint lists your collections of audio tracks and their basic attributes.",
        "operationId": "getSoundboxList",
        "summary": "List audio collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint creates one or more collections (soundboxes). To add tracks, use `POST /v2/audio/collections/{id}/items`.",
        "operationId": "createSoundbox",
        "summary": "Create audio collections"
      }
    },
    "/v2/audio/collections/{id}": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint deletes a collection.",
        "operationId": "deleteSoundbox",
        "summary": "Delete audio collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint gets more detailed information about a collection, including the number of items in it and when it was last updated. To get the tracks in collections, use `GET /v2/audio/collections/{id}/items`.",
        "operationId": "getSoundbox",
        "summary": "Get the details of audio collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint sets a new name for a collection.",
        "operationId": "renameSoundbox",
        "summary": "Rename audio collections"
      }
    },
    "/v2/audio/collections/{id}/items": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint removes one or more tracks from a collection.",
        "operationId": "deleteSoundboxItems",
        "summary": "Remove audio tracks from collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint lists the IDs of tracks in a collection and the date that each was added.",
        "operationId": "getSoundboxItems",
        "summary": "Get the contents of audio collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint adds one or more tracks to a collection by track IDs.",
        "operationId": "addSoundboxItems",
        "summary": "Add audio tracks to collections"
      }
    },
    "/v2/audio/genres": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint returns a list of all audio genres.",
        "operationId": "getGenres",
        "summary": "List audio genres"
      }
    },
    "/v2/audio/instruments": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint returns a list of all audio instruments.",
        "operationId": "getInstruments",
        "summary": "List audio instruments"
      }
    },
    "/v2/audio/licenses": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint lists existing licenses. You can filter the results according to the track ID to see if you have an existing license for a specific track.",
        "operationId": "getAudioLicenseList",
        "summary": "List audio licenses"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.create"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint gets licenses for one or more tracks.",
        "operationId": "licenseTrack",
        "summary": "License audio tracks"
      }
    },
    "/v2/audio/licenses/{id}/downloads": {
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint redownloads tracks that you have already received a license for.",
        "operationId": "downloadTracks",
        "summary": "Download audio tracks"
      }
    },
    "/v2/audio/moods": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint returns a list of all audio moods.",
        "operationId": "getMoods",
        "summary": "List audio moods"
      }
    },
    "/v2/audio/search": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint searches for tracks. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter.",
        "operationId": "searchAudio",
        "summary": "Search for tracks"
      }
    },
    "/v2/audio/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "audio"
        ],
        "description": "This endpoint shows information about a track, including its genres, instruments, and other attributes.",
        "operationId": "getTrack",
        "summary": "Get details about audio tracks"
      }
    },
    "/v2/contributors": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "contributors"
        ],
        "description": "This endpoint lists information about one or more contributors, including contributor type, equipment they use and other attributes.",
        "operationId": "getContributorList",
        "summary": "Get details about multiple contributors"
      }
    },
    "/v2/contributors/{contributor_id}": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "contributors"
        ],
        "description": "This endpoint shows information about a single contributor, including contributor type, equipment they use, and other attributes.",
        "operationId": "getContributor",
        "summary": "Get details about a single contributor"
      }
    },
    "/v2/contributors/{contributor_id}/collections": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "contributors"
        ],
        "description": "This endpoint lists collections based on contributor ID.",
        "operationId": "getContributorCollectionsList",
        "summary": "List contributors' collections"
      }
    },
    "/v2/contributors/{contributor_id}/collections/{id}": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "contributors"
        ],
        "description": "This endpoint gets more detailed information about a contributor's collection, including its cover image, timestamps for its creation, and most recent update. To get the items in collections, use GET /v2/contributors/{contributor_id}/collections/{id}/items.",
        "operationId": "getContributorCollections",
        "summary": "Get details about contributors' collections"
      }
    },
    "/v2/contributors/{contributor_id}/collections/{id}/items": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "contributors"
        ],
        "description": "This endpoint lists the IDs of items in a contributor's collection and the date that each was added.",
        "operationId": "getContributorCollectionItems",
        "summary": "Get the items in contributors' collections"
      }
    },
    "/v2/cv/images": {
      "post": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "computer_vision"
        ],
        "description": "This endpoint uploads an image for reverse image or video search. Images must be in JPEG or PNG format. To get the search results, pass the upload ID that this endpoint returns to the GET /v2/cv/similar/images or GET /v2/cv/similar/videos endpoints. Contact us for access to this endpoint.",
        "operationId": "uploadImage",
        "summary": "Upload images"
      }
    },
    "/v2/cv/similar/images": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "computer_vision"
        ],
        "description": "This endpoint returns images that are visually similar to an image that you specify or upload.",
        "operationId": "getSimilarImages",
        "summary": "List similar images"
      }
    },
    "/v2/cv/similar/videos": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "computer_vision"
        ],
        "description": "This endpoint returns videos that are visually similar to an image that you specify or upload.",
        "operationId": "getSimilarVideos",
        "summary": "List similar videos"
      }
    },
    "/v2/editorial/licenses": {
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.create"
            ]
          }
        ],
        "tags": [
          "editorial"
        ],
        "description": "This endpoint gets licenses for one or more editorial images. You must specify the country and one or more editorial images to license.",
        "operationId": "licenseEditorialImage",
        "summary": "License editorial content"
      }
    },
    "/v2/editorial/livefeeds": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "editorial"
        ],
        "operationId": "getEditorialLivefeedList",
        "summary": "Get editorial livefeed list"
      }
    },
    "/v2/editorial/livefeeds/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "editorial"
        ],
        "operationId": "getEditorialLivefeed",
        "summary": "Get editorial livefeed"
      }
    },
    "/v2/editorial/livefeeds/{id}/items": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "editorial"
        ],
        "operationId": "getEditorialLivefeedItems",
        "summary": "Get editorial livefeed items"
      }
    },
    "/v2/editorial/search": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "editorial"
        ],
        "description": "This endpoint searches for editorial images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchEditorial",
        "summary": "Search editorial content"
      }
    },
    "/v2/editorial/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "editorial"
        ],
        "description": "This endpoint shows information about an editorial image, including a URL to a preview image and the sizes that it is available in.",
        "operationId": "getEditorialImage",
        "summary": "Get editorial content details"
      }
    },
    "/v2/images": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists information about one or more images, including the available sizes.",
        "operationId": "getImageList",
        "summary": "List images"
      },
      "post": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "computer_vision"
        ],
        "deprecated": true,
        "description": "Deprecated; use `POST /v2/cv/images` instead. This endpoint uploads an image for reverse image search. The image must be in JPEG or PNG format. To get the search results, pass the ID that this endpoint returns to the `GET /v2/images/{id}/similar` endpoint.",
        "operationId": "uploadEphemeralImage",
        "summary": "Upload ephemeral images"
      }
    },
    "/v2/images/categories": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists the categories (Shutterstock-assigned genres) that images can belong to.",
        "operationId": "getImageCategories",
        "summary": "List image categories"
      }
    },
    "/v2/images/collections": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists your collections of images and their basic attributes.",
        "operationId": "getLightboxList",
        "summary": "List image collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint creates one or more image collections (lightboxes). To add images to the collections, use `POST /v2/images/collections/{id}/items`.",
        "operationId": "createLightbox",
        "summary": "Create image collections"
      }
    },
    "/v2/images/collections/featured": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists featured collections of specific types and a name and cover image for each collection.",
        "operationId": "getFeaturedLightboxList",
        "summary": "List featured image collections"
      }
    },
    "/v2/images/collections/featured/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint gets more detailed information about a featured collection, including its cover image and timestamps for its creation and most recent update. To get the images, use `GET /v2/images/collections/featured/{id}/items`.",
        "operationId": "getFeaturedLightbox",
        "summary": "Get the details of featured image collections"
      }
    },
    "/v2/images/collections/featured/{id}/items": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists the IDs of images in a featured collection and the date that each was added.",
        "operationId": "getFeaturedLightboxItems",
        "summary": "Get the contents of featured image collections"
      }
    },
    "/v2/images/collections/{id}": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint deletes an image collection.",
        "operationId": "deleteLightbox",
        "summary": "Delete image collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint gets more detailed information about a collection, including its cover image and timestamps for its creation and most recent update. To get the images in collections, use `GET /v2/images/collections/{id}/items`.",
        "operationId": "getLightbox",
        "summary": "Get the details of image collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint sets a new name for an image collection.",
        "operationId": "renameLightbox",
        "summary": "Rename image collections"
      }
    },
    "/v2/images/collections/{id}/items": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint removes one or more images from a collection.",
        "operationId": "deleteLightboxItems",
        "summary": "Remove images from collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists the IDs of images in a collection and the date that each was added.",
        "operationId": "getLightboxItems",
        "summary": "Get the contents of image collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint adds one or more images to a collection by image IDs.",
        "operationId": "addLightboxItems",
        "summary": "Add images to collections"
      }
    },
    "/v2/images/licenses": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists existing licenses. You can filter the results according to the type of license or the image ID.",
        "operationId": "getImageLicenseList",
        "summary": "List image licenses"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint gets licenses for one or more images. You must specify the image IDs in the body parameter and other details like the format, size, and subscription ID either in the query parameter or with each image ID in the body parameter. Values in the body parameter override values in the query parameters.",
        "operationId": "licenseImages",
        "summary": "License images"
      }
    },
    "/v2/images/licenses/{id}/downloads": {
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint redownloads images that you have already received a license for.",
        "operationId": "downloadImage",
        "summary": "Download images"
      }
    },
    "/v2/images/recommendations": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint returns images that customers put in the same collection as the specified image IDs.",
        "operationId": "getImageRecommendations",
        "summary": "List recommended images"
      }
    },
    "/v2/images/search": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint searches for images. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT. Free API accounts show results only from a limited library of media, not the full Shutterstock media library. Also, the[...]",
        "operationId": "searchImages",
        "summary": "Search for images"
      }
    },
    "/v2/images/updated": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint lists images that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show images that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.",
        "operationId": "getUpdatedImages",
        "summary": "List updated images"
      }
    },
    "/v2/images/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint shows information about an image, including a URL to a preview image and the sizes that it is available in.",
        "operationId": "getImage",
        "summary": "Get details about images"
      }
    },
    "/v2/images/{id}/similar": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "images"
        ],
        "description": "This endpoint returns images that are visually similar to an image that you specify.",
        "operationId": "getSimilarImages",
        "summary": "List similar images"
      }
    },
    "/v2/oauth/access_token": {
      "post": {
        "tags": [
          "oauth"
        ],
        "description": "This endpoint returns an access token for the specified user and with the specified scopes. The token does not expire until the user changes their password. The body parameters must be encoded as form data.",
        "operationId": "createAccessToken",
        "summary": "Get access tokens"
      }
    },
    "/v2/oauth/authorize": {
      "get": {
        "tags": [
          "oauth"
        ],
        "description": "This endpoint returns a redirect URI (in the 'Location' header) that the customer uses to authorize your application and, together with POST /v2/oauth/access_token, generate an access token that represents that authorization.",
        "operationId": "authorize",
        "summary": "Authorize applications"
      }
    },
    "/v2/test": {
      "get": {
        "tags": [
          "test"
        ],
        "operationId": "echo",
        "summary": "Echo text"
      }
    },
    "/v2/test/validate": {
      "get": {
        "tags": [
          "test"
        ],
        "operationId": "validate",
        "summary": "Validate input"
      }
    },
    "/v2/user": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "user.view"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "operationId": "getUser",
        "summary": "Get user details"
      }
    },
    "/v2/user/access_token": {
      "get": {
        "security": [
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "users"
        ],
        "operationId": "getAccessToken",
        "summary": "Get access token details"
      }
    },
    "/v2/user/subscriptions": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "purchases.view"
            ]
          }
        ],
        "tags": [
          "users"
        ],
        "operationId": "getUserSubsciptionList",
        "summary": "List user subscriptions"
      }
    },
    "/v2/videos": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists information about one or more videos, including the aspect ratio and URLs to previews.",
        "operationId": "getVideoList",
        "summary": "List videos"
      }
    },
    "/v2/videos/categories": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists the categories (Shutterstock-assigned genres) that videos can belong to.",
        "operationId": "getVideoCategories",
        "summary": "List video categories"
      }
    },
    "/v2/videos/collections": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists your collections of videos and their basic attributes.",
        "operationId": "getClipboxList",
        "summary": "List video collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint creates one or more collections (clipboxes). To add videos to collections, use `POST /v2/videos/collections/{id}/items`.",
        "operationId": "createClipbox",
        "summary": "Create video collections"
      }
    },
    "/v2/videos/collections/{id}": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint deletes a collection.",
        "operationId": "deleteClipbox",
        "summary": "Delete video collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint gets more detailed information about a collection, including the timestamp for its creation and the number of videos in it. To get the videos in collections, use GET /v2/videos/collections/{id}/items.",
        "operationId": "getClipbox",
        "summary": "Get the details of video collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint sets a new name for a collection.",
        "operationId": "renameClipbox",
        "summary": "Rename video collections"
      }
    },
    "/v2/videos/collections/{id}/items": {
      "delete": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint removes one or more videos from a collection.",
        "operationId": "deleteClipboxItems",
        "summary": "Remove videos from collections"
      },
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "collections.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists the IDs of videos in a collection and the date that each was added.",
        "operationId": "getClipboxItems",
        "summary": "Get the contents of video collections"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "collections.edit"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint adds one or more videos to a collection by video IDs.",
        "operationId": "addClipboxItems",
        "summary": "Add videos to collections"
      }
    },
    "/v2/videos/licenses": {
      "get": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists existing licenses. You can filter the results according to the type of license or the video ID.",
        "operationId": "getVideoLicenseList",
        "summary": "List video licenses"
      },
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.create",
              "purchases.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint gets licenses for one or more videos. You must specify the video IDs in the body parameter and the size and subscription ID either in the query parameter or with each video ID in the body parameter. Values in the body parameter override values in the query parameters.",
        "operationId": "licenseVideos",
        "summary": "License videos"
      }
    },
    "/v2/videos/licenses/{id}/downloads": {
      "post": {
        "security": [
          {
            "customer_accessCode": [
              "licenses.view"
            ]
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint redownloads videos that you have already received a license for.",
        "operationId": "downloadVideos",
        "summary": "Download videos"
      }
    },
    "/v2/videos/search": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint searches for videos. If you specify more than one search parameter, the API uses an AND condition. Array parameters can be specified multiple times; in this case, the API uses an AND or an OR condition with those values, depending on the parameter. You can also filter search terms out in the `query` parameter by prefixing the term with NOT.",
        "operationId": "searchVideos",
        "summary": "Search for videos"
      }
    },
    "/v2/videos/updated": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint lists videos that have been updated in the specified time period to update content management systems (CMS) or digital asset management (DAM) systems. In most cases, use the `interval` parameter to show videos that were updated recently, but you can also use the `start_date` and `end_date` parameters to specify a range of no more than three days. Do not use the `interval` parameter with either `start_date` or `end_date`.",
        "operationId": "getUpdatedVideos",
        "summary": "List updated videos"
      }
    },
    "/v2/videos/{id}": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint shows information about a video, including URLs to previews and the sizes that it is available in.",
        "operationId": "getVideo",
        "summary": "Get details about videos"
      }
    },
    "/v2/videos/{id}/similar": {
      "get": {
        "security": [
          {
            "basic": []
          },
          {
            "customer_accessCode": []
          }
        ],
        "tags": [
          "videos"
        ],
        "description": "This endpoint searches for videos that are similar to a video that you specify.",
        "operationId": "getSimilarVideos",
        "summary": "List similar videos"
      }
    }
  },
  "securityDefinitions": {
    "basic": {
      "type": "basic"
    },
    "contributor_accessCode": {
      "authorizationUrl": "https://contributor-accounts.shutterstock.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "collections.edit": "Grant the ability to create new collections, edit a collection, and modify the contents of a collection",
        "collections.view": "Grant read-only access to a collection and its contents.",
        "earnings.view": "Grant the ability to view a user's current earnings and payouts.",
        "licenses.create": "Grant the ability to download and license media on behalf of the user.",
        "media.edit": "Grant the ability to make changes to a user's existing approved media.",
        "media.submit": "Grant the ability to submit a user's uploaded media for review and check their approval states.",
        "media.upload": "Grant the ability to upload media to a user's account.",
        "user.address": "Grants read-only access to a user's physical address.",
        "user.edit": "Grants read and write access to all user account information.",
        "user.email": "Grants read-only access to a user's email address.",
        "user.view": "Grants read-only access to a user's basic account information (includes username, id, first and last name). If email is the same as username, it also implies user.email"
      },
      "tokenUrl": "https://contributor-accounts.shutterstock.com/oauth/access_token",
      "type": "oauth2",
      "x-shutterstock-realm": "contributor"
    },
    "customer_accessCode": {
      "authorizationUrl": "https://accounts.shutterstock.com/oauth/authorize",
      "flow": "accessCode",
      "scopes": {
        "collections.edit": "Grant the ability to create new collections, edit a collection, and modify the contents of a collection",
        "collections.view": "Grant read-only access to a collection and its contents.",
        "licenses.create": "Grant the ability to download and license media on behalf of the user.",
        "licenses.view": "Grant read-only access to a user's licenses.",
        "purchases.view": "Grant read-only access to a user's purchase history.",
        "user.view": "Grants read-only access to a user's basic account information (includes username, id, first and last name). If email is the same as username, it also implies user.email"
      },
      "tokenUrl": "https://api.shutterstock.com/v2/oauth/access_token",
      "type": "oauth2",
      "x-shutterstock-realm": "customer"
    }
  },
  "x-components": {}
}